### ISSUE TITLE
directly import google sheets via link

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#129]
### google sheet links

we often edit sheets collaboratively via google sheets now. at the moment, the procedure to import to formr means exporting to excel or CSV and then re-importing.

- [x] first step would be to permit pasting a link into a upload box (basically the link of a sheet that's shared via link, I want to steer clear of using the API for authentication and so on for now) and formr importing from there. here's a Stackoverflow answer that makes it look like a piece of cake http://stackoverflow.com/a/18106727/263054
- [x] second step would be storing such a link in the survey_studies table and offering the option to refresh items from the google sheet.

**Comment by rubenarslan** [comment]
Tried this on my local now. Looks great, but some follow-up:

1. I noticed that it isn't possible to update an existing study via a new Google sheet, 
2. nor is it possible to change the Google-sheet-Link in an existing study. This should be possible, since sheet names and addresses might change, and users might want to switch existing studies.
3. some odd bugs occur
      a. cannot reliable reproduce this yet: sometimes the dialog just doesn't get dismissed and nothing happens, when you click import
      b. for one sheet, where the sheet name was simply "survey" spreadsheet reader complained that it exceeded a 31-character constraint...

I can send you some links to various Google docs, to reproduce and test.

**Comment by cyriltata** [comment]
Update via google sheet is possible by clicking in the "Update from Google
Link" at the bottom of the import items page. And yes changing the google
link sheet is not possible because it is same as creating a new study. As
for the bugs you can send me links to test.

On Sat, Oct 17, 2015 at 12:26 PM, Ruben C. Arslan <notifications@github.com>
wrote:

> Tried this on my local now. Looks great, but some follow-up:
>
>    1. I noticed that it isn't possible to update an existing study via a
>    new Google sheet,
>    2. nor is it possible to change the Google-sheet-Link in an existing
>    study. This should be possible, since sheet names and addresses might
>    change, and users might want to switch existing studies.
>    3. some odd bugs occur a. cannot reliable reproduce this yet:
>    sometimes the dialog just doesn't get dismissed and nothing happens, when
>    you click import b. for one sheet, where the sheet name was simply "survey"
>    spreadsheet reader complained that it exceeded a 31-character constraint...
>
> I can send you some links to various Google docs, to reproduce and test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubenarslan/formr.org/issues/129#issuecomment-148898610>
> .
>



-- 
Cyril Tata
