### ISSUE TITLE
uploading somewhat larger ods file crashes non gracefully

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#130]
a white page turns up, the error log indicates that in excess of 1 GB of memory couldn't be allocated. seems a bit much for 400 items, but we should look into this.

> [19-May-2015 16:45:09 UTC] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 1069023197 bytes) in /var/www/formr.org/Model/Item.php on line 684
[20-May-2015 14:18:22 UTC] PHP Fatal error:  Call to a member function getNamespaces() on a non-object in /var/www/formr.org/vendor/phpoffice/phpexcel/Classes/PHPExcel/Reader/OOCalc.php on line 349

**Comment by rubenarslan** [comment]
please just wrap this in trycatch and give users a more sensible error msg (i.e. convert to different format, check whether they have excess empty columns).

**Comment by cyriltata** [comment]
Pls can you provide an example of such a file? Could not find one at random.

**Comment by cyriltata** [comment]
Also I see that there you mentioned a fatal error and these can't be wrapped in try..catch clauses. We should just configure a limit in the uploaded file.
