### ISSUE TITLE
store uploaded survey sheets and let users download the most recent one

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#177]
A few users have downloaded the normal form (with choices in a separate sheet) of the survey and were dismayed to find out that 
a) formatting is gone
b) choices are on second sheet
c) sometimes a re-upload of a normal form does not lead to the same result as the original upload (though I think this was mostly rating_buttons and we fixed that

**Comment by rubenarslan** [comment]
You implemented the backend, but as far as I can tell it's not in the view yet.

**Comment by cyriltata** [comment]
When you want to download items. There is a link to download original if it
is available. Or what do you mean by the view?

**Comment by rubenarslan** [comment]
oh sorry, I thought I was looking at a survey where I'd recently uploaded sth but I was not. But since we're on it, the view should, if available, have a link to the Google Sheet AND the most recent uploaded Google Sheet should also be stored and linked as the original upload I think.
