### ISSUE TITLE
more complete export and import of runs and surveys

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#182]
For backing up and version tracking and for runs in every case, we prefer JSON.

### Surveys
- [x] re-import of exported survey JSON works (and can include settings)
     - [ ] this may imply that we need to move some validation from the spreadsheet reader to the survey class.
- [x] export/import as spreadsheet and JSON should also include settings (as third sheet)
- [ ] POSTPONED: allow exporting spreadsheets including results (as fourth sheet), so people can easily share data with codebook
- [ ] POSTPONED: export as JSON should optionally include results (item display table)

### Runs
- [x] include surveys with all of the detail above, not just placeholders (but keep allowing those on import too)
- [x] include run settings
- [ ] POSTPONED: shuffle data (random groups)
- emails sent, cron messages? currently these aren't logged in all detail and I don't know who'd need this, could never be made public anyway. I think not, probably more for debugging.
- [x] uploaded files (just URIs)

This will enable us to have a run export which is full take of the study as it has taken place so far.

**Comment by rubenarslan** [comment]
I exported try_validation.xlsx from formr and then tried re-uploading the exported [try_validation.json.txt](https://github.com/rubenarslan/formr.org/files/7620/try_validation.json.txt) leads to a bunch of notices, probably related to validation that happens in spreadsheet reader instead of survey. Upload fails.

**Comment by cyriltata** [comment]
This is survey export I think.

On Mon, Oct 5, 2015 at 2:50 PM, Ruben C. Arslan <notifications@github.com>
wrote:

> I exported try_validation.xlsx from formr and then tried re-uploading the
> exported try_validation.json.txt
> <https://github.com/rubenarslan/formr.org/files/7620/try_validation.json.txt>
> leads to a bunch of notices, probably related to validation that happens in
> spreadsheet reader instead of survey. Upload fails.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubenarslan/formr.org/issues/182#issuecomment-145504333>
> .
>



-- 
Cyril Tata

**Comment by rubenarslan** [comment]
True, but it's identical to the export that's part of the run, right?

**Comment by cyriltata** [comment]
yes I think so. Maybe some subtle differences. My point is that you cannot
try to import a survey in json format.

On Mon, Oct 5, 2015 at 3:41 PM, Ruben C. Arslan <notifications@github.com>
wrote:

> True, but it's identical to the export that's part of the run, right?
>
> On Mon, Oct 5, 2015 at 2:29 PM Cyril <notifications@github.com> wrote:
>
> > This is survey export I think.
> >
> > On Mon, Oct 5, 2015 at 2:50 PM, Ruben C. Arslan <
> notifications@github.com>
> > wrote:
> >
> > > I exported try_validation.xlsx from formr and then tried re-uploading
> the
> > > exported try_validation.json.txt
> > > <
> >
> https://github.com/rubenarslan/formr.org/files/7620/try_validation.json.txt
> > >
> > > leads to a bunch of notices, probably related to validation that
> happens
> > in
> > > spreadsheet reader instead of survey. Upload fails.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/rubenarslan/formr.org/issues/182#issuecomment-145504333
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Cyril Tata
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/rubenarslan/formr.org/issues/182#issuecomment-145512285
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubenarslan/formr.org/issues/182#issuecomment-145515718>
> .
>



-- 
Cyril Tata

**Comment by rubenarslan** [comment]
But it should be possible or lead to a proper error message. I tend towards
__should be possible__, since people might also share survey JSON files on
their own.

**Comment by cyriltata** [comment]
yup.. maybe from the notices you can come up with some error points. I
think for now there is a check only for some particular properties in the
JSON object

On Mon, Oct 5, 2015 at 3:14 PM, Ruben C. Arslan <notifications@github.com>
wrote:

> But it should be possible or lead to a proper error message. I tend towards
> __should be possible__, since people might also share survey JSON files on
> their own.
>
> On Mon, Oct 5, 2015 at 3:04 PM Cyril <notifications@github.com> wrote:
>
> > yes I think so. Maybe some subtle differences. My point is that you
> cannot
> > try to import a survey in json format.
> >
> > On Mon, Oct 5, 2015 at 3:41 PM, Ruben C. Arslan <
> notifications@github.com>
> > wrote:
> >
> > > True, but it's identical to the export that's part of the run, right?
> > >
> > > On Mon, Oct 5, 2015 at 2:29 PM Cyril <notifications@github.com> wrote:
> > >
> > > > This is survey export I think.
> > > >
> > > > On Mon, Oct 5, 2015 at 2:50 PM, Ruben C. Arslan <
> > > notifications@github.com>
> > > > wrote:
> > > >
> > > > > I exported try_validation.xlsx from formr and then tried
> re-uploading
> > > the
> > > > > exported try_validation.json.txt
> > > > > <
> > > >
> > >
> >
> https://github.com/rubenarslan/formr.org/files/7620/try_validation.json.txt
> > > > >
> > > > > leads to a bunch of notices, probably related to validation that
> > > happens
> > > > in
> > > > > spreadsheet reader instead of survey. Upload fails.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/rubenarslan/formr.org/issues/182#issuecomment-145504333
> > > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Cyril Tata
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/rubenarslan/formr.org/issues/182#issuecomment-145512285
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/rubenarslan/formr.org/issues/182#issuecomment-145515718
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Cyril Tata
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/rubenarslan/formr.org/issues/182#issuecomment-145521636
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubenarslan/formr.org/issues/182#issuecomment-145523767>
> .
>



-- 
Cyril Tata
