### ISSUE TITLE
when item label is left empty, formr-ocpu-label is shown

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#209]
artifact of dynamic label generation even when label not dynamic

**Comment by rubenarslan** [comment]
To reproduce:

```csv
type,name,label
mc,dynamic,`r x`
mc,nondynamic,
```

The missing x causes an error, showing that the empty label was sent to openCPU.

**Comment by cyriltata** [comment]
What is best?
Keeping the original labels if an error occurs or setting to an empty string?
