### ISSUE TITLE
google import inconsistent

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#237]
- [x] unify interface
- [ ] fix backend
      - it seems to bypass some of our normal checks and balances, e.g. I had trouble when I changed an item from type note to type mc (it wasn't added to the results table).

**Comment by cyriltata** [comment]
I think we should refactor and remove the validation of items from the SpreadSheetReader in order not to duplicate code

**Comment by rubenarslan** [comment]
agree but thats bigger. I dont see why google sheet cannot be simply a diff approach to generate the local tempfile.
