### ISSUE TITLE
mailing_themselves in email does not work

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#257]
- users should be able to email themselves (e.g. for progress reports) all they want, without hitting our rate limit to protect against accidental spam.
- we currently allow this for emails to the email account that is sending the email and for emails to the run owner's email address

The latter is broken because we check Site::getCurrentUser instead of the run owner, but this doesn't make a lot of sense (most run users won't be registered).

**Comment by cyriltata** [comment]
which "users" should be able to email themselves? admins?(which I think it already the case) or participants?(in this case how?)

**Comment by rubenarslan** [comment]
it should be possible to set up the run so that notifications are sent to the admin. One of our users uses formr to send notifications to their own email account whenever one participant in a clinical study has completed their assignment.
So, we should turn off the spam-block for emails to a) the email account itself b) the run owner's email address.
a) works b) currently doesn't.

**Comment by rubenarslan** [comment]
closed in https://github.com/rubenarslan/formr.org/commit/1656293b50896672a6ccf623a13d363e0e1bb3e1
