### ISSUE TITLE
Improve reminder handling

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#262]
- [x] Log them in survey_unit_sessions: This way we can see when/if we sent reminders to a participant.
    - [x] show these logged reminders when choosing to send a reminder
- [x] make the button green when a reminder was sent (when sending multiple reminders, it's hard to keep track)
- [x] add API to send reminders to multiple participants.

**Comment by cyriltata** [comment]
Count of howmany times a reminder has been sent to some session has been added to the "Reminder Dialogue" when sending indivual reminders. This is not possible however when sending bulk reminders
