### ISSUE TITLE
escape email log

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#265]
a conditional comment of the form <!--[if mso]> broke my email log by escaping everything thereafter

**Comment by cyriltata** [comment]
emmm.. example of email that should produce such a comment blog? Also what you indicated there is invalid HTML comment so should indeed broke the html.

**Comment by rubenarslan** [comment]
We should just escape all HTML in those email logs, you can't just take half of an HTML document and respect syntax to be valid.
Or we could show the whole email in a scrollable field.
