### ISSUE TITLE
make variable such as user_last_time_active available

### ISSUE THREAD

**Issue by kthorstmann** [rubenarslan/formr.org#279]
As discussed in the [formr google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/formr/oQJrfUUUMJU), it would be nice to have a variable similar to `.formr$last_action_time` that allows seeing when then last time was that a user has done something actively, e. g. has responded to a survey.

It could for example be used to remove participants who have not responded to a number of invitations. 
Thanks!

**Comment by rubenarslan** [comment]
should be fixed via #283
