### ISSUE TITLE
survey_unit_sessions$position

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#280]
causes the following bug

> Column not found: 1054 Unknown column 'survey_unit_sessions.' in 'field list'

works with 2 columns

**Comment by cyriltata** [comment]
Why should survey_unit_sessions$position be valid? The position in survey_run_sessions can be used?

**Comment by rubenarslan** [comment]
In rare cases, this can be useful to compute how many times a user has been at a certain position in the run (e.g. text message reminders). We should make this simpler at some point, but for now, it's all we got.
