### ISSUE TITLE
Rethinking the run queue

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#298]
- [x] change run queue so that units that should expire compute the datetime on which they expire, then track unit expiry separately 
- [x] (also change R package functions that are used for date time stuff?)
- [x] separate session by run (path or subdomain)
- [x] subdomains for studies? #273

**Comment by cyriltata** [comment]
- certificate provider does not currently support wildcard sub-domains so we need to find other solutions.

**Comment by rubenarslan** [comment]
## Problems during testing

- [ ] Caching of Page results seems broken (regenerates every time).
- [ ] Preloading of Page results seems broken (Cron would run this, so that the result is precalculated and appears faster).

**Comment by rubenarslan** [comment]
- [ ] `next_day()` works with the new system
- [ ] access window using skipforward and "if user reacts"
- [ ] change how the "hour" function works in Pause?
- [ ] allow fractions of minutes in Pause? currently, we allow only full minutes. sometimes a 5 second wait is desirable to e.g. end an experience sampling survey or to show full page feedback, so people have to stop but will definitely go on if they reload.

**Comment by rubenarslan** [comment]
- [ ] add run module explanation for the 'wait for user' pause
- [ ] decide on wait for user pause icon

**Comment by rubenarslan** [comment]
For icons I tend towards one of

- Pause icon rotated sideways. 
  - Pro: Makes the connection clear
  - Neg: Meaning non-obvious?
- [Stopwatch](https://fontawesome.com/icons/user-clock?style=solid)/[Hourglass](https://fontawesome.com/icons/hourglass-half?style=solid), [User clock](https://fontawesome.com/icons/user-clock?style=solid)
   - Pro: Obvious meaning?
   - Neg: No real connection to boombox controls. Are they all in the FontAwesome release we're using right now?

**Comment by cyriltata** [comment]
Let's start with the icon decision "fa-hourglass-half" is present in our current FontAwesome release and the rest not. So maybe we could go with that?
