### ISSUE TITLE
potential improvements in "upload files" section of a run

### ISSUE THREAD

**Issue by doublermc** [rubenarslan/formr.org#332]
While working on my first formr project I two improvements to the "upload files" section of a run came to my mind:

- [x] A delete button for files that are not needed any longer (I couldn't find an option to delete files after two or three minutes of looking... even if there is an option for that it would benefit from higher visibility)

- [x] A way of displaying a file's URL in the "upload files" section without having to actually accessing the file in the browser. This would save a lot of time when pasting links to surveys. A button that says "copy URL" (cf. sharing options of google sheets) would be optimal, but a column that shows the URL itself would be an improvement as well.

**Comment by doublermc** [comment]
thank you, this is amazing!

**Comment by mpw-wwu** [comment]
What's left to be done here? There is a copy button, there is a delete button.

@rubenarslan, do you want to remove the popup, which comes up when copying a link? Or can this be closed.

@doublermc, I can't reproduce your issues deleting a file. Works perfectly for me.

**Comment by rubenarslan** [comment]
I assume @cyriltata got here first :-)
