### ISSUE TITLE
Item presentation bug

### ISSUE THREAD

**Issue by CaroZygar** [rubenarslan/formr.org#335]
Hi,

a month ago a participant reported an error with the presentation of the items in my survey. She was the only one who encountered that problem, so I don't know if it is just a special bug for a special browser version, but for the record I'll just report it here:

What should have looked like this:
![items_right](https://user-images.githubusercontent.com/18308979/37275323-22bf74ba-25df-11e8-8e08-2b1c9303b53b.jpg)
Looked like this on her Safari: Version 11.0.2 (13604.4.7.1.3):
![items_wrong](https://user-images.githubusercontent.com/18308979/37275327-26c203a2-25df-11e8-99fc-96fd3a41edc4.jpg)
The settings in formr look like this:

mc_heading   mc_aut | preaut |   |   |   |   | mc_width80     space_bottom_5
-- | -- | -- | -- | -- | -- | --
rating_button 1,5,1 | aut1 | In unserer Partnerschaft kann ich ohne größere   Einschränkungen machen, was ich will. |   | ! |   | mc_width80

mc_aut | 1 | __Trifft überhaupt   nicht zu__     __1__
-- | -- | --
  | 2 | __2__
  | 3 | __3__
  | 4 | __4__
  | 5 | __Trifft <br>   voll und ganz zu__     __5__

When she opened the questionnaire in Chrome, she encountered another problem.

What should have looked like this:
![items2_right](https://user-images.githubusercontent.com/18308979/37275442-865dc4a4-25df-11e8-9b49-e5ebebc1dda9.PNG)
Looked like this on her Google Chrome: Version 64.0.3282.186 (Offizieller Build) (64-Bit):
![items2_wrong](https://user-images.githubusercontent.com/18308979/37275449-8b93be42-25df-11e8-9e44-63c8a4c42126.jpg)

Settings in formr:

mc_heading   mc_csi2 | pre_csi2 |   |   |   |   | mc_width80     space_bottom_5
-- | -- | -- | -- | -- | -- | --
rating_button 1,6,1 | csi_5 | Wie oft sind Sie im   Allgemeinen der Ansicht, dass zwischen Ihnen und Ihrem Partner alles gut   läuft? | ! |   | blank_button     mc_width80     row_height_43

mc_csi2 | 0 | __nie__     __0__
-- | -- | --
  | 1 | __selten__     __1__
  | 2 | __gelegentlich__     __2__
  | 3 | __über-   wiegend__     __3__
  | 4 | __meistens__     __4__
  | 5 | __immer__     __5__

**Comment by rubenarslan** [comment]
We automatically switch to vertical presentation on narrow screens. Her screen is a bit narrow (although not as narrow as a smartphone for which we intended it). You can set the class `mc_horizontal` to prevent this, but it might render badly on phones.
