### ISSUE TITLE
Mailinator changed links again

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#339]
It's now
`https://www.mailinator.com/v2/inbox.jsp?zone=public&query=rjxbbzmhpmgs`

**Comment by cyriltata** [comment]
actually we should have our "Test Account" function to send a self-email.

**Comment by rubenarslan** [comment]
That's a better solution indeed.

**Comment by cyriltata** [comment]
Stopped using mailinator. Accounts are tested by sending a self-email.
