### ISSUE TITLE
sticky in value column does not work

### ISSUE THREAD

**Issue by selinakreinhard** [rubenarslan/formr.org#346]
we use sticky in the value column to show participants what value they chose before. Did work when we set it up (11.2017), but does not work any more. No value is highlighted, no error message returned (looks as if we would not use sticky at all). 

In addition, Ruben wrote a small js script. Using this, we required our participants to select a value (to avoid that participants select the same value out of laziness). This script also does not work any more. 

webshim.ready('DOM forms forms-ext dom-extend', function () {
    window.setTimeout(function() {
    $(":checked").prop("checked", false);
    }, 10);
});
see "Is it possible to show participants how they answered the same item earlier in the run?" here https://github.com/rubenarslan/formr.org/wiki/FAQ---frequently-asked-questions

[sticky_example.xlsx](https://github.com/rubenarslan/formr.org/files/1979983/sticky_example.xlsx)

let me know if you need more info.

**Comment by cyriltata** [comment]
@selinakreinhard With which _item type_ did you face this issue?
