### ISSUE TITLE
display problem for stored items of type tel with more than 11 digits

### ISSUE THREAD

**Issue by selinakreinhard** [rubenarslan/formr.org#347]
we store a phone number as itemtype tel and want to show the number on the next page.
Works fine if tel number contains 11 digits, but display format is off (e.g. 1.234567910^{10} ) for more than 11 digits. Results table looks normal, so I'd  assume its a display issue. 

[tel_display_error.xlsx](https://github.com/rubenarslan/formr.org/files/2038849/tel_display_error.xlsx)

**Comment by mpw-wwu** [comment]
R has an auto conversation from strings to numbers. If you have any non digit character like +,/,-( oder ) in your phone number, this doesn't happen.

I don't really see the point of having a Tel.php class if it does accept letters anyway ;).

**Comment by selinakreinhard** [comment]
Thanks for your reply. I'd like to avoid non-digit characters because we use this phone numbers later in the run to send text messages. Do you know of other alternatives, i.e. can I stop auto conversion for this item somehow? 
I use tel because of the nice phone symbol. :)

**Comment by rubenarslan** [comment]
It seems this is a problem with formrs excel export specifically? Is
information actually lost or just not cast right?

>

**Comment by MPW1412** [comment]
@rubenarslan, no, the number is stored correctly (even with the missing leading zero) in the database as a 100 char string. I tested that earlier.

This is just a problem with the output in the web application. (And I haven't verified an export yet, maybe there aswell.)

We should check with other applications and standards what kind of signs are typically allowed in phone numbers. I'd at least allow ”+“ for the international format. And consider allowing / and -, which could be easily removed while sms sending.

**Comment by MPW1412** [comment]
Ups, well, mpw1412 is my private account, mpw-wwu my working account btw.^^

**Comment by mpw-wwu** [comment]
Both the export and the display in the show results area are correct. It's really just the display error when the field is reused like @selinakreinhard does.

**Comment by mpw-wwu** [comment]
@selinakreinhard, you can mitigate the problem by using

`r toString(PC1_phonenumber)`

in your survey spreadsheet. But you'll still lack the leading zero, if there had been one.

@rubenarslan, this is an interesting point for me. How do R, opencpu and the PHP part of formR interact?

I haven't stumbled across the code yet, where R gets the database connection or just the data. At that point, it should be specified to strictly treat this type as string or character and it must not be type converted to number as R likes to do it.

At the point, where the dynamic r code string is embedded into the body of the R function, it's already to late. The information about the leading zero is already gone. And as far as I know, you can't access the raw input anymore (correct me if I'm wrong).

**Comment by rubenarslan** [comment]
I'm not sure where this problem occurs. In the DB we store Tels as character strings. https://github.com/rubenarslan/formr.org/blob/ded34c605cb3d1a79fdf3cb094a1c7f1c50499f4/application/Model/Item/Tel.php 

We don't export to Excel via R (as you know), but I'm assuming Excel tries to be smart. Maybe there's something we can do about this to set it explicitly.

When making data available in R, we use the function `opencpu_define_vars`.
https://github.com/rubenarslan/formr.org/blob/master/application/Library/Functions.php#L904

We currently use the flag JSON_NUMERIC_CHECK. This probably causes conversion of phone numbers into numbers, with loss of leading zeroes. I'd have to run some tests to see whether it can be disabled (i.e. whether the JSON we generate in PHP already correctly types variables).

**Comment by selinakreinhard** [comment]
> you can mitigate the problem by using `r toString(PC1_phonenumber)` in your survey spreadsheet.

It did not occur to me that I can simply change the label of my note Item, thanks @mpw-wwu !

> But you'll still lack the leading zero, if there had been one. 

I'll include a zero at the beginning `r paste0("0", PC1_phonenumber)` . That is sufficient for our purpose

> You might assume that people enter mobile phone numbers and just add an extra zero, if there's none, when sending the text messages.

The numbers seem to be stored correctly. So as far as I understand it, there is no need to change my external module for text messages. At least to my knowledge, no error with sending text messages occurred so far.

**Comment by mpw-wwu** [comment]
I'm happy, that it works. But I think we should fix this anyway.

**Comment by mpw-wwu** [comment]
@rubenarslan, @cyriltata, this issue was assigned to me. Ruben already gave the solution, removing the JSON_NUMERIC_CHECK flag.

I'm not really the right person to decide if this causes side effects. Do you want me to create a test branch, so we all could give this a shot? Or how do we want to do this?

**Comment by rubenarslan** [comment]
I think we can test it as part of this hotfix. For example, given that my last work on this was so long ago, I'm not sure whether numbers that we also store as numbers are properly cast without the flag.

**Comment by cyriltata** [comment]
So anyone found side effects yet? I haven't really dug into this

**Comment by mpw-wwu** [comment]
No time yet to dig into this.

**Comment by cyriltata** [comment]
do you by any chance have a sample survey sheet to replicate this? I can test the various scenarios.

**Comment by rubenarslan** [comment]
all_widgets should work?

**Comment by cyriltata** [comment]
Well I removed the json_encode numeric check. Items of type number are validated as numbers before saved anyway so I don't think if sent to R will have an issue.

**Comment by mpw-wwu** [comment]
> do you by any chance have a sample survey sheet to replicate this?

First post on this site.

**Comment by mpw-wwu** [comment]
The bug is gone. Not sure about side effects.

**Comment by rubenarslan** [comment]
Can you simply do a test using all_widgets, then add a stop button, list
all variables and show me the result of str(all_widgets)?

**Comment by mpw-wwu** [comment]
@rubenarslan, 

[FormrTestSheet.txt](https://github.com/rubenarslan/formr.org/files/2396513/FormrTestSheet.txt)

That's the Google Docs Demo Sheet filled out by monkey bar. Seems fine for me.

**Comment by mpw-wwu** [comment]
Part of release v0.17.18.
