### ISSUE TITLE
rename run doesn't change run's name in browser tab

### ISSUE THREAD

**Issue by Tschulie** [rubenarslan/formr.org#349]
We've renamed our run and it's worked only for the URL but not for the browser tab's name. It's still the old name. 
We've tried separately it in two different runs using two different accounts, but renaming has never affected the tab's name.

**Comment by cyriltata** [comment]
@Tschulie Please for now use the Run Settings > Title to specify what should show on the browser tab. This will be fixed subsequently

**Comment by rubenarslan** [comment]
Maybe this should be wontfix, as the title can be changed independently. Or we only change the title if it's still the default.

**Comment by rubenarslan** [comment]
I think we should let title and name be independent.
