### ISSUE TITLE
email module: Recipient not found (if email not entered in first, but in following row)

### ISSUE THREAD

**Issue by selinakreinhard** [rubenarslan/formr.org#350]
run includes survey (asking for email-address) and email module. 
We use this run for phone screening, so if we do not reach participants, we cannot include their email address, but instead stop the survey and try to reach them later.

If the email address is not given in the first row, but in a following row, the email cannot be sent (after completing the survey in the second try) and an error message is shown "We could not find an email recipient. Session: [session Id]" 
the email address is correctly stored in the results, but it seems as if the email module cannot access it. 
Problem occurs if Recipient-Field: nameofsurvey$nameofemailitem
Does not occur for Recipient-Field: last(nameofsurvey$nameofemailitem)
let me know if you need more info.

**Comment by rubenarslan** [comment]
This is expected behaviour. If you don't want last, use first. Both will
take the first/last nonmissing email address.

**Comment by selinakreinhard** [comment]
Thanks! was not expected by me at first, but I see now how this makes sense.
