### ISSUE TITLE
formR doesn't run with libsodium23

### ISSUE THREAD

**Issue by mpw-wwu** [rubenarslan/formr.org#352]
Hello,
as discussed in the Google Group Mailinglist, formR doesn't run with libsodium23 as it is shipped with Ubuntu 18.04.

The php-headers don't seem to be the problem. Despite of the [suggestion from here](https://github.com/paragonie/halite/issues/48) to force version 2.0.8, formR seems to run perfectly with 2.0.11 on Debian 9.

The problem seems to be the library libsodium itself provided by the operating system. 

Debian 9's libsodium18 package is based on version 1.0.11. Ubuntu 16.04's libsodium23 package is based on version 1.0.14.

I've gone through the changelog: https://github.com/jedisct1/libsodium/blob/master/ChangeLog#L110

The line that cought my attention is line 110 ”scrypt was removed from minimal builds.“

A quick grep though formR's source code shows the use of functions with scrypt in their names. This is probably the point.

I'm not really familiar with scrypt, can someone provide intel on what these functions are for and whether they could be replaced by others? Relying on manually compiled libraries isn't really comfortable.

I'll try to compile libsodium23  with scrypt-support to see, whether it runs.

Regards,
Matthias

**Comment by mpw-wwu** [comment]
Update: Ubuntu ships libsodium with minimal-configuration, so scrypt is not part of libsodium23.

I removed the ”--enable-minimal“ from nativeclient-x86_64.sh in libsodium-1.0.16/dist-build, recompiled and voilà, it works.

The documentation of libsodium suggests to not use scrypt unless you have specified reasons to do so. Do we have such reasons for formR? I guess sodium is just used to hash the password here. I think that should be replaceable by Argon2 as the documentation suggests.

I'm not sure whether that would break database integrity. At least for new installations, it should be no problem to use a different hashing algorithm.

**Comment by mpw-wwu** [comment]
Work left to be done: Create script to migrate old databases to new halite version.

**Comment by mpw-wwu** [comment]
I think this issue can be closed, as @cyriltata migrated the database already?

**Comment by cyriltata** [comment]
I think we should just leave it open till the changes are migrated to
production

**Comment by cyriltata** [comment]
formr now requires PHP 7.2 so this can be closed
