### ISSUE TITLE
Run lock: r-code in modules not locked

### ISSUE THREAD

**Issue by selinakreinhard** [rubenarslan/formr.org#355]
although the run is locked, r code in modules is still editable. I would prefer the lock feature to lock  all parts required for problem-free data collection.
(I'd also like the lock button to change into a closed lock if the run is locked, but that is more of a visual preference)

**Comment by mpw-wwu** [comment]
Hello Selina,

all the text fields seem to be grayed out but are still editable although changes are not saved. Even if you click ”save“. This is indeed a little unclean.

See you,
Matthias

**Comment by mpw-wwu** [comment]
I just looked into this a little further.

The elements that are properly disabled, are of type input. But non-disabled elements are of type textarea. Somehow the flag disabled is not passed on to them.

Maybe @rubenarslan knows which library is responsible for this?

**Comment by mpw-wwu** [comment]
Tested on test.formr.org → fixed ✓

**Comment by mpw-wwu** [comment]
Part of release v0.17.18.
