### ISSUE TITLE
Export Of Runs Broken

### ISSUE THREAD

**Issue by mpw-wwu** [rubenarslan/formr.org#356]
Hello,

I noticed today, that the export function for formR for runs is broken. Snippet of the created JSON file:

```
{
    "name": "Testexport",
    "units": [
        {
            "type": "Survey",
            "description": "Modul_Versuchspersonencode",
            "position": 1,
            "special": ""
        },
        {
            "type": "Survey",
            "description": "Emailtest",
            "position": 2,
            "special": ""
        },
[...]
```
The JSON lacks the fields unit_id and run_uni_id which leads to broken runs in case of reimport:

![bildschirmfoto von 2018-07-10 14-20-25](https://user-images.githubusercontent.com/40468459/42509870-8871bb98-844d-11e8-94ea-2b9ace5f6b99.png)

They are explicitly removed in the run class' export function:

`unset($unit->unit_id, $unit->run_unit_id);`

The code was written by @cyriltata in 2015 in ef86f74ad.

I don't understand, why the IDs are removed and why this export function is treated like a static function although it is not? Why is there a run passed to the export-Function although it could be addressed via $this?

I'd like to refractor this area and solve the export bug. But first I wanted to ask if there was a thought behind the concept, why were they removed?

I'd suggest to remove the arguments of the export function and address the run via $this. 

It's clear, that they can't be imported to other instances of formR, but at least they could be re-imported to the same instance.

Regards,
Matthias

**Comment by rubenarslan** [comment]
Hi Matthias, the run export was mainly intended to share study structures with other people and accounts. So, the IDs are removed on purpose. 
There is a check mark at the top, which governs whether surveys should be exported with all items and settings or not. The default is not, but that's a debatable default I think. 
If you check this checkbox, the run export should recreate the study elsewhere, but independently of the creator account.
As for the object passing, you'll have to ask @cyriltata

**Comment by mpw-wwu** [comment]
Okay, yeah I had thought that there was an intention behind.

So your idea was to select the surveys by hand, after the logic has been imported automatically.

It could be tried to match the survey by name. That would make the function more unusable. Because as it is now, it becomes less and less useful the longer the run is. But you'd only need the export function for long runs.

I guess I'll close this issue here as my issue is not a bug but intended to be like that. And I'll propose a PR for the function parameters and we can discuss the code still there.

**Comment by rubenarslan** [comment]
@mpw-wwu initially, I thought re-use of surveys across studies would be common. Turns out, it's not. Probably the default should be to make the run exports self-contained instead of containing only placeholders for surveys. However, I don't think it's good to re-link surveys, because people don't expect this. The latter option is mainly interesting for us as devs when we try to give people "patterns" to re-use.

**Comment by mpw-wwu** [comment]
The main interest I had, was to easily copy whole runs in order to experiment with its logic furthermore without destroy status quo.

**Comment by mpw-wwu** [comment]
But wouldn't that copy the whole survey module?

**Comment by rubenarslan** [comment]
Yes. I think that is usually intended, but your tests are a special case.
