### ISSUE TITLE
Survey import complains about CSS classes that are available

### ISSUE THREAD

**Issue by mpw-wwu** [rubenarslan/formr.org#361]
When importing a spreadsheet with rotate_label45 and mc_width70, formR complains about non-standard CSS classes, although those two classes are listed in config/css-classes.php:

`mc_heading_selbstbericht' You used CSS classes that aren't part of the standard set (but maybe you defined them yourself): rotate_label45 mc_width70`

I haven't had time to debug this yet, so this is just a reminder for later.

**Comment by rubenarslan** [comment]
I cannot reproduce this. Maybe you use a non-space white-space, which would also explain why the classes aren't concatenated by comma in the warning. But I cannot reproduce it by copy-pasting a tab character into an Excel sheet either.

**Comment by mpw-wwu** [comment]
I just checked the file, in my case they were separated by carriage return (U+000D). I think, we can close this.
