### ISSUE TITLE
allow 2 emails in 10 minutes

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#373]
modify rate limit for this use case

> So I'm doing a followup study. The participant receives an invitation via email to complete the next survey. Suppose he/she clicks on the link immediately and enters the study. He/she completes the survey in less than 10 minutes, and receives feedback via email again (so 2 emails are sent in less than 10 minutes).

**Comment by mpw-wwu** [comment]
Fine with me. But didn't we plan to route all emails through the new queue?

**Comment by mpw-wwu** [comment]
Sounds reasonable
