### ISSUE TITLE
time_stayed in user detail is wrong

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#378]
it's apparently relative to today, should be relative to expired time.

**Comment by rubenarslan** [comment]
As column names, I'd prefer `seconds_stayed` and lowercase `entered` and `left`.

**Comment by mpw-wwu** [comment]
Done ✓

https://github.com/rubenarslan/formr.org/commit/4ce61590f41b73152c2f89c517efc5c8ccc5dde3

**Comment by mpw-wwu** [comment]
Part of release v0.17.18.
