### ISSUE TITLE
Trouble: maxType, maxChoose & label_align_xy in comb. with answer_below_label

### ISSUE THREAD

**Issue by RichardWundrack** [rubenarslan/formr.org#382]
Hi,

I stumbled across a class and a type problem in formr. Here you find a [toy example](https://docs.google.com/spreadsheets/d/1gGqYeZRpB2t-0gaTVeRjH1TslfF6qjzdngpDmSFPen8/edit?usp=sharing) presenting both problems if you upload and run it in *test survey*.

The first problem is that the maxType and maxChoose specification of select_or_add_one/multiple do not work for my example. E.g. if I limit maxType to 5 instead of the default of 255 it counts through my 3 choices five times eventually offering me only the 2nd choice. If I limit maxType to 5 and maxChoose to 2 it somehow just merges all answers.

The second problem is that I cannot align the label with the center or the right after choosing the answer_below_label class.

Thank you so much for your help!

Best,
Richard

**Comment by mpw-wwu** [comment]
Hello Richard,

I can confirm every single of your issues. Thanks for reporting and
providing the demo sheet!

Could you please open separate issues for each problem?
https://github.com/rubenarslan/formr.org/issues

Best,
Matthias

Matthias P. Walther
Psychologisches Institut · Technische Dienste · Informationstechnik
Tel.: 0251 83-34133
Raum: 74

Verschlüsselte Emails: Ich kann sowohl PGP- als auch S/MIME-verschlüsselte
Emails senden und empfangen. Meine PGP-Identität lautet A9D012A90145CA65.

Am 31.08.2018 um 15:18 schrieb RichardWundrack:

**Comment by RichardWundrack** [comment]
Sorry, for the delay, I will do it now. I hope it is enough to split it up into two issues and not into all the permutations of the problems listed?
