### ISSUE TITLE
center / right label impossible after choosing answer_below_label

### ISSUE THREAD

**Issue by RichardWundrack** [rubenarslan/formr.org#391]
Hi,
Here you find a [toy example](https://docs.google.com/spreadsheets/d/1gGqYeZRpB2t-0gaTVeRjH1TslfF6qjzdngpDmSFPen8/edit#gid=0) that I cannot align the label with the center or the right after choosing the answer_below_label class.

Thank you so much for your help!

Best,
Richard

**Comment by selinakreinhard** [comment]
adding !important made it work for me
e.g.
form.form-horizontal div.label_align_center .control-label {
    text-align: center !important;
    padding-left: 5px;
}
