### ISSUE TITLE
bug: note_iframe is believed to have a results table column

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#392]
Item of type `note_iframe` don't yield a results table column, but when a user requests them, formr tries to find one, yielding a fatal error. apparently, this is still hard-coded, which it shouldn't be.
![image](https://user-images.githubusercontent.com/831109/45827402-aae65a80-bcf6-11e8-9166-a0b4ffbd91ec.png)

**Comment by cyriltata** [comment]
Probably this happens for all types that are not stored in DB (note, .. etc)?

**Comment by rubenarslan** [comment]
no we have a flag for this at the item class level. it works for note, block, and submit, but apparently not for note_iframe. 
the item cannot have values and should thus be ignored when looking for result columns
