### ISSUE TITLE
Run Export: Valid export names unclear + Default name potentially invalid

### ISSUE THREAD

**Issue by selinakreinhard** [rubenarslan/formr.org#398]
In Edit Run - Export - Enter a name for your export and select run units
it is apparently not allowed to use hyphens (-) for export names. If I do so, an error message appears "Export name invalid. Enter a valid export name"

I'd like 
- the error message to be more specific. What symbols are allowed?

And/or
- the default name to always be a valid export name. Currently the default name is just the name of the run, which can contain hyphens.

**Comment by mpw-wwu** [comment]
Hello,

I don't see a reason, why a hyphen should not be allowed in a filename.
I'd suggest to remove this limitation.

Can you open an issue for this?
https://github.com/rubenarslan/formr.org/issues

Best,
Matthias

Matthias P. Walther
Psychologisches Institut · Technische Dienste · Software-Entwicklung
Tel.: 0251 83-34133
Raum: 74

Verschlüsselte Emails: Ich kann sowohl PGP- als auch S/MIME-verschlüsselte
Emails senden und empfangen. Meine PGP-Identität lautet A9D012A90145CA65.

Am 10.10.2018 um 11:41 schrieb selinakreinhard:

**Comment by rubenarslan** [comment]
just a holdover from when we didnt use subdomains, then runs only allowed a-z0-9_, now it's a-z0-9-
