### ISSUE TITLE
Generalise file upload in run

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#403]
We need the following changes to the file upload in the run

- [ ] file links should be served via the subdomain of the study now that we have subdomains. old links should hard redirect (to avoid XSS)
- [ ] we can then allow upload of HTML, JS, CSS, PDF files (no worries about cross-site scripting)
- [ ] For people who just want to upload stimulus1 to 50, or people who upload HTML and PDFs, we need to make the file name randomisation optional. It's probably needed less often than normal names are requested.

**Comment by rubenarslan** [comment]
this comes up quite often, we mask the file names, but this is really mainly a feature to get anonymity. it isn't always desired and comes at the price of meaningless file names. we also no longer need the long names to prevent conflicts between runs. in the future, files should be accessible under study-name.formr.org/assets/file1.jpg etc unless the automatic masking is desired.

**Comment by mpw-wwu** [comment]
I'm not sure, if this is a good idea. People could easily rip all files from a run. The user/researcher might not always be aware of that. I don't like bossing around the user, but in this case it might make sense.

It's become kind of standard to obfuscate the paths to files nowadays.

**Comment by rubenarslan** [comment]
People keep asking and we can explain. It's a minority of users so far for
whom obfuscation was even a concern. And it's very annoying to substitute
in all the filenames for 100 stimuli..

**Comment by rubenarslan** [comment]
If we implement this, it will be much easier for users to integrate with lab.js and jsPsych.
