### ISSUE TITLE
Log of user activity: delete unit confirmation window error

### ISSUE THREAD

**Issue by selinakreinhard** [rubenarslan/formr.org#404]
If l click Log of user activity -> delete (x), a confirmation window opens ("Are you sure you want to delete this unit session?")
If I confirm (click ok), I get an alert window ("Success. You deleted this unit session.") -> expected 
However, if I do not confirm (click cancel), I get the same alert window ("Success. You deleted this unit session.") and the unit session vanishes from the log of user activity -> not expected
I tried this multiple times, let me know if you need more info.

**Comment by rubenarslan** [comment]
whoah! can reproduce, thanks!

**Comment by mpw-wwu** [comment]
This bug is...weird. First I thought the problem was the wrongly used quotation marks. But even with the correct syntax, the entry is still deleted. I copied just the link for deletion into a seperate html, where it worked. Seems to be caused by some CSS or JS from Formr.

**Comment by rubenarslan** [comment]
Yes, we need to fix the JS.

**Comment by cyriltata** [comment]
I plan for a general hotfix on Thursday when I return to address all
indicated bugs
