### ISSUE TITLE
Create Table survey_users fails. Duplicate first_name, last_name and affiliation

### ISSUE THREAD

**Issue by dmcgowandmc** [rubenarslan/formr.org#418]
When testing in my own environment, the following step:

mysql formr -uformr -pEnterPassword < /path/to/formr/sql/schema.sql

fails with a Duplicate first_name error in the survey_users table

Checking the SQL, first_name, last_name  and affiliation are repeated. 

CREATE TABLE `survey_users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_code` char(64) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  **`first_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `affiliation` varchar(50) DEFAULT NULL,**
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  **`first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `affiliation` VARCHAR(350) NULL,**
  `admin` tinyint(1) DEFAULT '0',
  `email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email_verification_hash` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `email_verified` tinyint(1) DEFAULT '0',
  `reset_token_hash` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `reset_token_expiry` datetime DEFAULT NULL,
  `mobile_number` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mobile_verification_hash` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mobile_verified` tinyint(1) DEFAULT '0',
  `referrer_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_code_UNIQUE` (`user_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

**Comment by cyriltata** [comment]
@dmcgowandmc the sql merge behaved weird in this case. Thanks for pointing out. This will be updated in the upcoming release. For the mean time you can use the attached updated scheme 
[schema.sql](https://github.com/rubenarslan/formr.org/files/3280874/schema.sql.txt)

**Comment by dmcgowandmc** [comment]
Thanks @cyriltata
