### ISSUE TITLE
Changing the size of mc_button

### ISSUE THREAD

**Issue by Ria90** [rubenarslan/formr.org#419]
Is it possible to change the size of pictures in FormR? 
![image](https://user-images.githubusercontent.com/50833362/59530484-f7587280-8ee3-11e9-98bb-eed9764878ff.png)
For this item I have used mc_button. But I need to make them a little smaler. Can somebody help me?

**Comment by rubenarslan** [comment]
Please ask questions like this on the google group providing an example of your survey sheet.
