### ISSUE TITLE
No export of  detailed results possible

### ISSUE THREAD

**Issue by doublermc** [rubenarslan/formr.org#422]
I cannot export the detailed results. I have tried it several times and for several formats, but I always get: 

500

Fatal Error

A fatal error occured and your request could not be completed. Contact site admins with these details
Error [1] in /var/www/formr.org/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Collection/Cells.php line 395
Maximum execution time of 30 seconds exceeded

Is this a bug?
My user name is "peerstudy@uni-leipzig.de"
The survey name is "OTAPE3".

Thanks for your support. Cheers!

**Comment by cyriltata** [comment]
@doublermc please can you try again?

**Comment by doublermc** [comment]
@cyriltata yes, it worked now! thank you!
