### ISSUE TITLE
Hi!   for one of my studies, i am making button matrices as item choices and i want to align them side by side on the run page and not in a vertical manner, so it is spread out throughout the page. How do i align items side by side and not vertically?

### ISSUE THREAD

**Issue by Sham-2818** [rubenarslan/formr.org#424]
Please briefly describe your problem and what output you expect. 
If you have a question, please don't use this form, but instead ask on the mailing list <https://groups.google.com/forum/#!forum/formr>. 
If you have a question that is not really about formr, but about using R, consider https://stackoverflow.com for support.

If you are describing a feature request, please try to make very clear what you want the new feature to accomplish and 
give your use case for which it'd help.
If you are describing a problem or bug, please try to make it reproducible for us. Ideally this means, 
that you reduce the problem to a minimal example that still causes the problem you're trying to fix. 

Delete these instructions once you have read them.

**Comment by Sham-2818** [comment]
[item.docx](https://github.com/rubenarslan/formr.org/files/3610322/item.docx)

**Comment by rubenarslan** [comment]
answered on mailing list
