### ISSUE TITLE
Make number of rows in a survey available in R

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#425]
We currently only have `.formr$nr_of_participants` which is less useful than it could be, because it also includes people who only looked at the study once.
For people who e.g. want to set a quota on a study (e.g. maximum participants), it's probably better to be able to get the total N of people who finished a survey.

**Comment by cyriltata** [comment]
Myabe we can rely on SurveyUnit$ended attribute?

**Comment by rubenarslan** [comment]
Yeah, although I just realised we need both no. started and no. ended. If you store `ended` while within a survey, multiple people can get the same number.

**Comment by rubenarslan** [comment]
implemented with the `iteration` column in new surveys.
