### ISSUE TITLE
Error messages in German in Safari browser

### ISSUE THREAD

**Issue by alanjern** [rubenarslan/formr.org#426]
If a user fails to complete a question, the message that appears ("Bitte wählen Sie eine Option aus.") is in German rather than the local language when I open the survey in Safari. The message is in English when I open the survey in Firefox.

**Comment by rubenarslan** [comment]
use `webshim.activeLang('en');` in run settings JS

see
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/formr/06P_Qq1MJjc
