### ISSUE TITLE
Emails not sent

### ISSUE THREAD

**Issue by RP1attachment** [rubenarslan/formr.org#427]
Hello,

I have been running my study with formr last spring for few months. We basically want participants to receive emails about a study and click on the link to access the study. Everything went smoothly back then. We stopped for the summer. Now, few days ago, we re-started data collection and the participants are not receiving the emails anymore. Do you know what can be wrong? We did not change anything in the program, so it should work as it did few months ago.
Emails are supposed to be sent via a gmail account, 

Thank you!

Francesca

**Comment by cyriltata** [comment]
Hello  Francesca,

For such things it is preferable to send a support ticket to the formr
support group formr<at>googlegroups.com . Please do that and we follow up
from there.

Regards
Cyril

**Comment by RP1attachment** [comment]
Hi Cyril,

Ok thank you, I wrote a post in the google group then

Cheers,

Francesca
