### ISSUE TITLE
500 Fatal Error when trying to export data. 

### ISSUE THREAD

**Issue by SamGuay** [rubenarslan/formr.org#430]
Hi, 

When I try to view or export my output data, here's an error I have never gotten in the past with the same survey: 
> 500
> Fatal Error
> 
> 2019-10-23 20:36:44
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 's23573_Neuropsy_dataentry_global.RLRI_RIM_RepCorrectes' in 'field list'.
> Please let the administrators and know what you were trying to do and provide this message's date & time.

I can find the _RLRI_RIM_RepCorrectes_ in the Google Form, so I am not to sure what to do next. From what I remember, I haven't added this column recently.

Let me know if you need more details,

Thank you,

Samuel

**Comment by cyriltata** [comment]
Hi Samuel

Can you see the column " RLRI_RIM_RepCorrectes " in the results table of
the survey  " RLRI_RIM_RepCorrectes " ?

**Comment by SamGuay** [comment]
Hi,

Thanks for your reply. When I created the run a long time ago, I just created a really [long google sheet](https://docs.google.com/spreadsheets/d/1NcAECx7bxzlJ8j6YO37Dw3nZ4bN0zFtHQCLB_5G-s4Q/edit?usp=sharing), so I don't think there is a survey called "RLRI_RIM_RepCorrectes". In fact, it's just a data point (line 223). 

I should have at least 50 different replies by now, so I'm getting a bit worried.

Cheers,

**Comment by cyriltata** [comment]
Sorry I meant the following survey " Neuropsy_dataentry_global  " ?

**Comment by SamGuay** [comment]
I see the row in the survey as I indicated in the previous comment. If you have a look at the [google sheet here](https://docs.google.com/spreadsheets/d/1NcAECx7bxzlJ8j6YO37Dw3nZ4bN0zFtHQCLB_5G-s4Q/edit?usp=sharing), you can see it at line 223. However, I cannot access any result since this error 500. 

Thanks, once again

**Comment by cyriltata** [comment]
Dear Samuel

I will like to debug this further by sending you some information and I
can't do so publicly. Can you send me a private email and we continue from
there?
best
Cyril
