### ISSUE TITLE
SQL Error: Row size too large

### ISSUE THREAD

**Issue by jmgirard** [rubenarslan/formr.org#431]
I am trying to use the following Google spreadsheet to create a form:
https://docs.google.com/spreadsheets/d/1f9yxYMjb9blF2Tvm6KD7NVxGiohf7JGrVAnIZAdMbx0/edit?usp=sharing

However, when I try to import these items, I get the following error:
> Error: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large (> 8126). Changing some columns to TEXT or BLOB may help. In current row format, BLOB prefix of 0 bytes is stored inline.

Based on the link below, I think this may be related to the MySQL `innodb_log_file_size` setting: https://stackoverflow.com/questions/22637733

**Comment by cyriltata** [comment]
Dear Jeffrey

Our administrators impose limits on our servers to prevent abuse and are
not able to circumvent. What I will recommend you do is try to split your
survey into 2 or so and add them one after another in the run definition.
This will make no difference to the participant. You can always reference
the responses of a preceding survey in the next.

Best
Cyril

**Comment by jmgirard** [comment]
I'm fine with that solution in principle. However, I'd like to understand why this error is occurring for my specific worksheet. It doesn't seem like overly much data to me: just 315 rows and 6 columns. Perhaps there is something wrong in how I've configured it?

**Comment by cyriltata** [comment]
Technically the data is not stored as you define your excel sheet. Some
processing transforms your excel sheet to the actual data structure and
this has its limitations.
There is nothing "wrong" per say in your excel sheet. The combination of
number of rows and the specified item types just exceed the limit the
storage engine can handle.

**Comment by jmgirard** [comment]
I was able to streamline things a lot by removing the redundant `style` options from each `<video>` tag and applying these options using the Run's custom CSS options instead.
