### ISSUE TITLE
Fifth page in survey is always blank

### ISSUE THREAD

**Issue by jmgirard** [rubenarslan/formr.org#432]
I have a survey that runs through multiple pages that all have the same format: display an HTML5 video in a `note` item, several `text` items, and then a `submit` button item. This works well for the first four pages but then strangely the fifth one goes to a blank page with none of these item displayed. There doesn't seem to be an issue with the fifth video, however, because it happens even if I shuffle the video's ordering. The Item List also looks fine. Any clues for troubleshooting?

SurveyID: 30568
tBVCj6BPYs

Here is what the fifth page looks like (blank):
![pg5](https://user-images.githubusercontent.com/6829033/67706448-2b15cf80-f98f-11e9-97a1-eddf9a65b4e7.png)

**Comment by cyriltata** [comment]
Dear Jeffery

Please could you privately send me your items sheet let me try to replicate
the problem? I don't have access to your study on formr.

best
Cyril

**Comment by jmgirard** [comment]
Sure, Cyril. What is your preferred email address?

**Comment by jmgirard** [comment]
To follow up for documentation purposes, this ended up being related to my use of `hidden` items. Removing these items resolved the issue.
