### ISSUE TITLE
hide_label for mc_multiple broken

### ISSUE THREAD

**Issue by mpw-wwu** [rubenarslan/formr.org#434]
Grouping mc_multiple items with hide_label doesn't seem to work anymore.

[mc_grouped.xlsx](https://github.com/rubenarslan/formr.org/files/3824103/mc_grouped.xlsx)

![Bildschirmfoto vom 2019-11-08 11-24-33](https://user-images.githubusercontent.com/40468459/68469406-654a6100-021a-11ea-9046-2d30952b53c1.png)

**Comment by MarleneKammerer** [comment]
Hi, I am encountering the same problem in my survey (in which I use plenty of mc multiple questions). Cp. screenshot! I was wondering if you have an idea when this bug will be fixed? Kind regards and many thanks. Marlene

![grafik](https://user-images.githubusercontent.com/44803690/71971545-1ebdb680-320b-11ea-829b-9d54c336de8b.png)

**Comment by cyriltata** [comment]
Hi Marlene

for now can you use Run > Settings > CSS to fix this?
best
Cyril

**Comment by MarleneKammerer** [comment]
Thanks for your quick response. I can try, but maybe you could guide me a little? I am not so proficient in CSS, yet.
Thank you
Marlene

Universität Bern
Oeschger Centre for Climate Change Research (OCCR)
Institut für Politikwissenschaft (IPW)

Marlene Kammerer
Post-Doc, Dr. phil

Fabrikstrasse 8
CH-3012 Bern

Tel. +41 (0)31 631 48 22
mailto: marlene.kammerer@ipw.unibe.ch

https://www.ipw.unibe.ch/ueber_uns/personen/dr_kammerer_marlene/index_ger.html
http://www.oeschger.unibe.ch/about_us/people/personalpage/index_eng.html?id=558

Recent papers:

Ingold, Karin; Varone, Fréderic; Kammerer, Marlene; Metz, Florence; Kammermann, Lorenz; Stroz, Chantal, 2019: Are responses to official consultations and stakeholder survey reliable guides to policy actors’ positions? September 2019, Policy & Politics, 10.1332/030557319X15613699478503

Kammerer, Marlene & Namhata, Chandreyee, 2018: What drives the Adoption of Climate Change Mitigation Policy? A Dynamic Network Approach to Policy Diffusion, Policy Sciences, 51(4), 10.1007/s11077-018-9332-6

Von: Cyril <notifications@github.com>
Gesendet: Mittwoch, 8. Januar 2020 13:38
An: rubenarslan/formr.org <formr.org@noreply.github.com>
Cc: Kammerer, Marlene (IPW) <marlene.kammerer@ipw.unibe.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [rubenarslan/formr.org] hide_label for mc_multiple broken (#434)

Hi Marlene

for now can you use Run > Settings > CSS to fix this?
best
Cyril

**Comment by cyriltata** [comment]
could you send the link to your run

**Comment by MarleneKammerer** [comment]
https://landkreisgemeinde.formr.org/

Universität Bern
Oeschger Centre for Climate Change Research (OCCR)
Institut für Politikwissenschaft (IPW)

Marlene Kammerer
Post-Doc, Dr. phil

Fabrikstrasse 8
CH-3012 Bern

Tel. +41 (0)31 631 48 22
mailto: marlene.kammerer@ipw.unibe.ch

https://www.ipw.unibe.ch/ueber_uns/personen/dr_kammerer_marlene/index_ger.html
http://www.oeschger.unibe.ch/about_us/people/personalpage/index_eng.html?id=558

Recent papers:

Ingold, Karin; Varone, Fréderic; Kammerer, Marlene; Metz, Florence; Kammermann, Lorenz; Stroz, Chantal, 2019: Are responses to official consultations and stakeholder survey reliable guides to policy actors’ positions? September 2019, Policy & Politics, 10.1332/030557319X15613699478503

Kammerer, Marlene & Namhata, Chandreyee, 2018: What drives the Adoption of Climate Change Mitigation Policy? A Dynamic Network Approach to Policy Diffusion, Policy Sciences, 51(4), 10.1007/s11077-018-9332-6

Von: Cyril <notifications@github.com>
Gesendet: Mittwoch, 8. Januar 2020 13:42
An: rubenarslan/formr.org <formr.org@noreply.github.com>
Cc: Kammerer, Marlene (IPW) <marlene.kammerer@ipw.unibe.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [rubenarslan/formr.org] hide_label for mc_multiple broken (#434)

could you send the link to your run

**Comment by cyriltata** [comment]
Can you change the session code staring with  HW9RaQSDE.....  to a test
session? Or you can navigate with this session to the items of interest and
let me know

**Comment by MarleneKammerer** [comment]
I am sorry Cyril, but I don’t get what I am supposed to do ☹. It’s my first steps in formR.

Universität Bern
Oeschger Centre for Climate Change Research (OCCR)
Institut für Politikwissenschaft (IPW)

Marlene Kammerer
Post-Doc, Dr. phil

Fabrikstrasse 8
CH-3012 Bern

Tel. +41 (0)31 631 48 22
mailto: marlene.kammerer@ipw.unibe.ch

https://www.ipw.unibe.ch/ueber_uns/personen/dr_kammerer_marlene/index_ger.html
http://www.oeschger.unibe.ch/about_us/people/personalpage/index_eng.html?id=558

Recent papers:

Ingold, Karin; Varone, Fréderic; Kammerer, Marlene; Metz, Florence; Kammermann, Lorenz; Stroz, Chantal, 2019: Are responses to official consultations and stakeholder survey reliable guides to policy actors’ positions? September 2019, Policy & Politics, 10.1332/030557319X15613699478503

Kammerer, Marlene & Namhata, Chandreyee, 2018: What drives the Adoption of Climate Change Mitigation Policy? A Dynamic Network Approach to Policy Diffusion, Policy Sciences, 51(4), 10.1007/s11077-018-9332-6

Von: Cyril <notifications@github.com>
Gesendet: Mittwoch, 8. Januar 2020 14:02
An: rubenarslan/formr.org <formr.org@noreply.github.com>
Cc: Kammerer, Marlene (IPW) <marlene.kammerer@ipw.unibe.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [rubenarslan/formr.org] hide_label for mc_multiple broken (#434)

Can you change the session code staring with HW9RaQSDE..... to a test
session? Or you can navigate with this session to the items of interest and
let me know

**Comment by cyriltata** [comment]
could you send an email to my private address?

**Comment by AlicieAD** [comment]
HI! Recently found the same issue, ended up using a quick fix: putting a single full stop in the "label" column (it is barely noticeable in some cases). Thought it might help to write it here!
