### ISSUE TITLE
`r ...` block in pause text blocks css

### ISSUE THREAD

**Issue by mpw-wwu** [rubenarslan/formr.org#435]
If there is an `r ...` block in the pause's text, the study page header will not be loaded.

Works:

> Ihre Studie beginnt heute um bla Uhr.
> 
> Ihr EMOTIONS-Team
> 

Doesn't work:

> Ihre Studie beginnt heute um `r library(lubridate)
> if (wday(Sys.Date()) %in% c(1, 7)) {
>     morgens_stunden<-EMOTIONS_Zeiten_abfragen$morgens_stunden_we
>     morgens_minuten<-EMOTIONS_Zeiten_abfragen$morgens_minuten_we
> } else {
>     morgens_stunden<-EMOTIONS_Zeiten_abfragen$morgens_stunden
>     morgens_minuten<-EMOTIONS_Zeiten_abfragen$morgens_minuten
> }
> paste(morgens_stunden,sprintf("%02d", morgens_minuten), sep=":")
> ` Uhr.
> 
> Ihr EMOTIONS-Team

**Comment by xpressio** [comment]
I have been experiencing the same issue - have you found any solution for this?

**Comment by cyriltata** [comment]
@xpressio please can you show your code?

**Comment by xpressio** [comment]
A simple example where I ran into problems:

`
`r ifelse(demographics$gender == 1, 'Liebe Frau', 'Lieber Herr')` `r demographics$name`,

vielen Dank, Sie haben die erste Sitzung unserer Studie erfolgreich abgeschlossen.
`

The expected information (i.e. gender and name) are returned correctly, the page's CSS appears broken though (all white, no header picture).

**Comment by cyriltata** [comment]
When there is r code in the pause script then the pause is displayed in an iframe so maybe this could be causing the issue. Well closing this as stale but if needs to be re-opened while attaching the r script and debug data
