### ISSUE TITLE
cron.php incompatible to new run queue

### ISSUE THREAD

**Issue by mpw-wwu** [rubenarslan/formr.org#436]
Cron.php is not compatible with the queing system, e. g. returning a timestamp from a pause modul doesn't work when an instance runs with cron. Recode cron.php in a way that it calls the new queue or remove it.

Design decision, @rubenarslan 

My suggestion would be to just remove it. We're a small team. We should focus on features not on hosting related stuff.

**Comment by cyriltata** [comment]
The cron feature has been deprecated and should be used only for older versions of formr
