### ISSUE TITLE
API calls can exceed available memory

### ISSUE THREAD

**Issue by martinmodrak** [rubenarslan/formr.org#438]
I am experimenting with FormR API. And it turns out, I cannot download the results from one of my surveys, which is large-ish (~300 rows in the item table, ~1800 responses). Accessing from R, I run:

```r
formr_api_access_token(client_id = api_secret$id, client_secret = api_secret$secret)

request <-
        list(
                "run[name]" = 'roverskypruzkum',
                "surveys[hlavni_dotaznik]" = ""
)

odpovedi <- formr_api_results(request)
```

And the response is a XML document containing:

```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 53659488 bytes)
```

For other surveys I have, I don't run against the limit and get the results as expected. Also, when I try to download only few items from the survey, it works great. 

This is currently not blocking my work in any way, but I thought I'd let you know. Thanks for the amazing work on FormR, it is great stuff.

My guess as to the cause:
It looks like you are constructing the whole response before sending it. I've had similar problems when sending large files from PHP and the solution was to 1) stream the contents instead of loading the whole response into memory and 2) turning output buffering off (`ob_end_flush`). Hope that helps.

**Comment by cyriltata** [comment]
Hello Martin,

Please could you try your operation again?

best
Cyril

**Comment by martinmodrak** [comment]
Yes, it works now, great!
