### ISSUE TITLE
the classes "label_align_center" and "answer_align_center" do not work for all item types

### ISSUE THREAD

**Issue by LudwigOhse** [rubenarslan/formr.org#439]
I'm using "label_align_center" for item type "note" and the class combination "answer_below_label + label_align_center + answer_align_center" for several item types.

However, "label_align_center" and "answer_align_center" do not work for all item types:
- "label_align_center" does not work for item type "note";
- "answer_align_center" does not work for item types "text", "textarea", "number" and "letters" ("Simple input family"); and it does not work for item types "select_one" and "select_multiple" ("Multiple choice family").

Here, you can see an example Google spreadsheet (with a selection of item types): https://docs.google.com/spreadsheets/d/1gwKYbX-yXPR558u6S2ZrlIuCTYiEsbaFPXXMNOONDwE/edit#gid=1611481919
Here, you can inspect a formr run, based on the example Google spreadsheet: https://align-commands.formr.org/

I am aware of this topic: https://groups.google.com/forum/#!searchin/formr/label$20align|sort:date/formr/2Xd-lGhE90A/mldYDpE6AAAJ
But the proposed CSS code did not work for me when I tried to center an item of item type "note" (I am not familiar with CSS). --> see the example Google spreadsheet
However, I found a way to center a "note" by marking it as an heading (e. g. "##### Welcome to my study!") and using this CSS code: "H5 { text-align: center }".  --> see the example Google spreadsheet

But - If I am not totally wrong - there must be an issue with "label_align_center" and "answer_align_center".
Is there a general solution for that?
Or is there a solution using CSS code (that is easy, so I can apply it)?

Best, Ludwig

**Comment by rubenarslan** [comment]
Hi Ludwig,

this seems like a bug in our CSS. I'll try to look into it after parental
leave. Would be great
if you could lodge a Github bug report to remind me.

You can force center alignment using custom CSS like the following:

form.form-horizontal div.form-group.form-row.item-note.label_align_center
div.control-label, form.form-horizontal
div.form-group.form-row.item-note_iframe.label_align_center
div.control-label {
    text-align: center!important;
}

.label_align_center .form-control, .label_align_center textarea {
    margin-left: auto;
    margin-right: auto;
}


Best,

Ruben

**Comment by rubenarslan** [comment]
Hi Ludwig,

this seems like a bug in our CSS. I'll try to look into it after parental
leave. 
You can force center alignment using custom CSS like the following:

```
     form.form-horizontal div.form-group.form-row.item-note.label_align_center
     div.control-label, form.form-horizontal
     div.form-group.form-row.item-note_iframe.label_align_center
     div.control-label {
         text-align: center!important;
     }

    .label_align_center .form-control, .label_align_center textarea {
        margin-left: auto;
        margin-right: auto;
    }
```

**Comment by LudwigOhse** [comment]
Hi Ruben,

thanks a lot! The CSS code works very well!

Best, Ludwig
