### ISSUE TITLE
Randomize order of response options

### ISSUE THREAD

**Issue by jacob-long** [rubenarslan/formr.org#440]
As far as I can tell, `formr` facilitates two kinds of question randomization: 1. randomizing the order in which questions appear and 2. randomizing the order in which groups of questions appear. Another oft-used form of questionnaire randomization concerns the ordering of response options.

For instance, I might ask, "Which of these is your favorite color?" and offer "red," "blue," and "green" as options. Because I worry that weak preferences will create a bias for the first listed response, I'd like to randomly shuffle the order in which the colors appear. 

Again, as far as I can tell, this isn't possible short of implementing some complex logic of creating multiple otherwise-equivalent questions and using random number generation to choose which version (which would probably be preferable under some conditions). I wonder if it would be possible to add a column-based on/off type of option to randomize the order of responses. Sometimes someone might prefer more granular control over the response choices (e.g., randomize order of "red" and "blue" but make "green" always last) but that would probably be too painful to implement to be worth it.

**Comment by cyriltata** [comment]
Closing as stale and also use the group [formr support group](https://groups.google.com/g/formr) for such requests.
