### ISSUE TITLE
Export and show Data round 0.5 to 1

### ISSUE THREAD

**Issue by Steffen-F** [rubenarslan/formr.org#442]
Hey there!

So what did i try?
I used range_ticks 0,12,0.5 to get data. 
But when i looked at my data with the implemendet show data button, all numbers were rounded.
So 0.5 went straigt up to 1.
Same diffculties with exporting the data als xls and csv.

But when you look at the detailed data, in formr. numbers are not rounded.

attached ist a survey you can use to reproduce my problem. 

[Testsheet.xlsx](https://github.com/rubenarslan/formr.org/files/4292374/Testsheet.xlsx)

Greetings Yeso

**Comment by cyriltata** [comment]
Dear Steffen,

I think the formatting happens only at the level of excel and maybe you
will need to manually format the cells when you open the file with your
spreadsheet client.
best
Cyril

**Comment by Yesowitsch** [comment]
Dear Cyril,

the following things didn`t help:
Exporting it as pdf and reading it with the Windows10 texteditor. -> Only integers-
opening it in excel and formatting cells to number cells. -> Only integers
Exporting it as csv and opening it in Windows10 texteditor. -> Onyl integers.

Point is: When i go on show results, where formr shows me my results, its only integers aswell. 
             So maybe its the way, formr stores the data of range_tickes?

Best
Yeso

**Comment by cyriltata** [comment]
Dear Yeso

Can you try using JSON export?

best
Cyril

**Comment by cyriltata** [comment]
Closing this issue as it is stale

**Comment by rubenarslan** [comment]
I could reproduce this. The number-type items do their own thing determining a result field, which was being overridden by the `getResultField` function. 

@Steffen-F if you lost real data this way, the proper answers should still be recoverable from the "detailed results", which were not affected by this bug.

**Comment by Steffen-F** [comment]
Hey Ruben,

I did not loose real data, i went over "detailed results" as you mentionend.
Good to hear it was a bug and got fixed!
