### ISSUE TITLE
Extra space added to bottom of mc_button items with line breaks in choice label

### ISSUE THREAD

**Issue by jmgirard** [rubenarslan/formr.org#444]
When adding a line break to my `mc_button` items' choice labels, extra space gets added to the end. I'd like to find a way to remove this extra space (perhaps through CSS).

Input (link):
https://docs.google.com/spreadsheets/d/1ymxeosqfuAz5KEkLbrrSZahBKzAVQOzEnUc-HYJfFgU/edit?usp=sharing

Input (screenshot):
![image](https://user-images.githubusercontent.com/6829033/76798539-25861e00-67a6-11ea-9751-e36db061a806.png)

Output (screenshot):
![image](https://user-images.githubusercontent.com/6829033/76798506-17380200-67a6-11ea-98d7-6c427ec88328.png)

Output (code):
```
<button type="button" class="btn" data-for="item7536655_1">
    <span class="btn_value">1</span>
    <span class="btn_label"><p>Button<br />1</p></span>
</button>
<button type="button" class="btn" data-for="item7536655_2">
    <span class="btn_value">2</span>
    <span class="btn_label"><p>Button<br />2</p></span>
</button>
```

**Comment by cyriltata** [comment]
Dear Jeffery

Yes you could add your own CSS in Run > Settings > CSS tab.

best
Cyril

**Comment by jmgirard** [comment]
Thanks Cyril. I will look into the CSS. Any pointers to what classes or properties to modify? Based on the code above, I would probably start with the "btn" class.

**Comment by cyriltata** [comment]
Try 
```
.btn p {
   margin-bottom: 0;
}
```

**Comment by jmgirard** [comment]
That fixed it. Thanks! (Should this be default?)
