### ISSUE TITLE
In EHC study: mermaid gantt chart wont display

### ISSUE THREAD

**Issue by hheyenn** [rubenarslan/formr.org#446]
Hi,
have been testing my Event History Calendar Survey a month ago and again now. Using the same xls files, js and css settings, the gantt chart showed in test runs in February, but not now. Instead the output is as following: 

gantt
title Overview of residences
dateFormat YYYY-MM-DD
section Residences
Rome : done , a1 , 2010-01-01 , 2015-01-01
Paris : done , a2 , 2015-02-01 , 2017-02-01
Berlin : active , a3 , 2017-03-01 , 2020-03-24

Here the corresponding r code in my spreadsheet:
```{r}     gannt_event_row <- function (i, data, col_title, col_datefrom,   col_dateto, col_current) {         empty <- ''              if(!(paste0(col_title, i) %in%   colnames(data))) {             return (empty)             }              title <- last(data[paste0(col_title,   i)])         if (is.na(title) \|\| title == '')   {             return (empty)         }              is_current <-   last(data[paste0(col_current, i)]) == 1         datefrom <-   last(data[paste0(col_datefrom, i)])           dateto <- ifelse(is_current,   format(Sys.Date(), "%Y-%m-%d"), last(data[paste0(col_dateto,   i)]))         tag <- ifelse(is_current,   "active", "done");         label <- paste0("a",   i)              paste(title, ":", tag,   ",", label, ",", datefrom, ",", dateto,  "       ", sep = " ")     }          residences <- NULL;     for (x in 1:last(My_EHC_survey$count_SR)) {         residences <- c(residences,   gannt_event_row(x, My_EHC_survey, 'residence_R', 'datefrom_R', 'dateto_R',   'current_residence_R'))     }          ```     <div class="formr-mermaid">          gantt         title Overview of   residences         dateFormat  YYYY-MM-DD         section Residences        `r paste(residences,   collapse="\n")`     </div>
--

Please let me know if some changes in form r may be causing this. Or what the corresponding human error could be on my side. 
Thank you!

**Comment by cyriltata** [comment]
Can you check if your JavaScript is upto date? Maybe you can also send a
link to your study.

**Comment by hheyenn** [comment]
Works in the live study now, thanks! Gantt chart is showing, though still not in test mode.

**Comment by hheyenn** [comment]
The issue is back.

**Comment by hheyenn** [comment]
I am having the same problem again. The gantt wont show testing the original  my ehc study by Wiezorek et al. here: https://ehcrun.formr.org/

Using Firefox and JS up to date version.

Can you please help fix the problem and let me know what the cause it so I can adapt it in my own ehc studies?

Thank you,

Hannah

**Comment by cyriltata** [comment]
Hello Hannah

The mermaid.js is now available.

best
Cyril

**Comment by hheyenn** [comment]
I am having the gantt problem again with my new study. Could  you make the mermaid available  again?
In addition the other survey in the run stopped turning past page one. Although it did in testing in another run earlier.
https://mobile-lives-survey2023.formr.org/?code=Y5zuPFhSep9GFa_hxGfs8cKSiiMod63gZlUZiXB3bnuSB3WZuhxqTS4RbWUENTN0
Hope you can help!

Thank you,
