### ISSUE TITLE
External Link Does Not Proceed to Next Unit

### ISSUE THREAD

**Issue by yuesaka** [rubenarslan/formr.org#448]
As per discussion in https://groups.google.com/forum/#!topic/formr/uFJq_LHGR90:

Repro steps:
1. Start the run with new user
2. The user is directed to google
3. Go to the Edit Run page > Users
4. observe the position of the new user

Expected:
The new user should be in the pause block

Actual:
The new user is still in the external link block

Below is a study where the first item is an external link where "api_end" is false.
Seems like JSON files are not support on github, so here's the run since it's so short:
`{
    "name": "pauseBugRun",
    "units": [
        {
            "type": "External",
            "description": "",
            "position": 10,
            "special": "",
            "external_link": "https:\/\/www.google.com",
            "api_end": 0,
            "expire_after": 0
        },
        {
            "type": "Pause",
            "description": "",
            "position": 20,
            "special": "",
            "wait_until_time": "",
            "wait_until_date": "",
            "wait_minutes": 1,
            "relative_to": "",
            "body": "In pause"
        },
        {
            "type": "Endpage",
            "description": "",
            "position": 30,
            "special": "",
            "body": "End of study"
        }
    ],
    "settings": {
        "header_image_path": null,
        "description": null,
        "footer_text": "Remember to add your contact info here! Contact the [study administration](mailto:email@example.com) in case of questions.",
        "public_blurb": null,
        "cron_active": 1,
        "custom_js": "",
        "custom_css": ""
    },
    "files": []
}`

**Comment by yuesaka** [comment]
And for reference, if I set the expiration (which I'm not a 100% sure what this means in this context), the result is still the same

Run with 1 minute expiration set:

`
{
    "name": "pauseBugRun",
    "units": [
        {
            "type": "External",
            "description": "",
            "position": 10,
            "special": "",
            "external_link": "https:\/\/www.google.com",
            "api_end": 0,
            "expire_after": 1
        },
        {
            "type": "Pause",
            "description": "",
            "position": 20,
            "special": "",
            "wait_until_time": "",
            "wait_until_date": "",
            "wait_minutes": 1,
            "relative_to": "",
            "body": "In pause"
        },
        {
            "type": "Endpage",
            "description": "",
            "position": 30,
            "special": "",
            "body": "End of study"
        }
    ],
    "settings": {
        "header_image_path": null,
        "description": null,
        "footer_text": "Remember to add your contact info here! Contact the [study administration](mailto:email@example.com) in case of questions.",
        "public_blurb": null,
        "cron_active": 1,
        "custom_js": "",
        "custom_css": ""
    },
    "files": []
}
`

**Comment by cyriltata** [comment]
@yuesaka 

I tested your code above here is what I realised:
- user gets redirected to google
- try to access the run with that same user and then you will see the pause

I agree that the count only shows up in the External unit until you revisit the run with the access code before you see a count on the Pause unit. In summary if your users are redirected back to formr after they leave with the External unit then they should see the Pause

**Comment by yuesaka** [comment]
Hi @cyriltata 
Thanks for looking into it!

Yes, in my actual study I redirect the user back to the run, which puts most user into the pause block properly.

The issue is that some users don't always complete the external link portion to the end, causing them to not be redirected back to the run, thus the run is stuck on the external link until the next the user comes back, and then they are presented with the pause screen. 

Either way, thanks for looking into this, and I hope the bug is fixed soon!
Best,
Yuma

**Comment by rubenarslan** [comment]
I didn't look at the code for this, but I agree it's an unexpected and unpredictable behaviour, probably introduced when we switched up the run queueing, so would be good to go back to the old behaviour (close external unit sessions after redirection).
