### ISSUE TITLE
Fatal Error 500 : Unable to export data

### ISSUE THREAD

**Issue by shivanikhanna04** [rubenarslan/formr.org#449]
I'm unable to export data for my complete run.

The error displayed is

500
Fatal Error

A fatal error occured and your request could not be completed. Contact site admins with these details
Error [1] in /var/www/formr.org/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Collection/Cells.php line 395
Maximum execution time of 240 seconds exceeded

My survey link is https://personality1.formr.org/

Hoping for a solution. Cheers!

**Comment by shivanikhanna04** [comment]
It's been a week and the error persists. I've tried different browsers as well.

Any  suggestions?

**Comment by cyriltata** [comment]
Hello, our system administrators are still working to resolve the execution
issue. Please give us some time to adjust this

**Comment by rubenarslan** [comment]
@shivanikhanna04 in the meantime, please use the export capabilities of the individual surveys. sorry, we're overstretched at the moment.

**Comment by jmgirard** [comment]
I am getting an error on export run data: "503 Feature Unavailable: Sorry this feature is temporarily unavailable. Please try again later." Is this related to this issue or a different one?

**Comment by cyriltata** [comment]
For users with very huge datasets, please export individual surveys as @rubenarslan suggested.
