### ISSUE TITLE
If email is not authenticated, message sending fails silently

### ISSUE THREAD

**Issue by jacob-long** [rubenarslan/formr.org#450]
I've been running a study for several months and things had been going quite smoothly (great job you all do!). This is a daily diary survey in which participants are emailed a link every morning. Almost a month ago, the email credentials for the account used to send emails expired and therefore for that period of time there were no emails sent. 

It is not the fault of formr that the credentials expired — that is an IT policy at my institution that requires changes to passwords every 180 days. But what I would have liked formr to do is signal to me in some way that the emails were not sending so I didn't burn through almost a month of volunteers who were not getting follow-up emails.

I'm not sure that this is a "bug" because I have a suspicion that the way the email is implemented may prevent formr from even knowing that it has failed. But I want to put this on your radar as something that can happen.

**Comment by rubenarslan** [comment]
hi @jacob-long sorry to hear, that must hurt. it's on our radar to look into this, but we mainly recommend to stay enrolled in your own study while you're running it, because email sending can fail in many places we cannot check (we can check authentication, but not spam folders etc)
