### ISSUE TITLE
Installation Issues - opencpu.conf issue & db schema import fails

### ISSUE THREAD

**Issue by smcgrat** [rubenarslan/formr.org#451]
Hello, sorry if I am doing something wrong here. I would appreciate any help available please.

I'm following the instructions at https://github.com/rubenarslan/formr.org/blob/master/INSTALLATION.md and getting some problems unfortunately.

1. opencpu.conf issue

* How to reproduce

While following the instructions the following line did not work in my experience, there were no location statements in the `/etc/opencpu/server.conf` file
> Open /etc/opencpu/server.conf using e.g., sudo nano. Remove the first location block and replace it with ...

I added what was recommended anyway. But then the webserver was then not accessible and needed those entries removed to work a gain.

Might the relevant file instead be `/etc/apache2/sites-available/opencpu.conf` but the additions look like nginx statements not apache!

* Expected behavior

Webserver working

* Actual behavior

Browsing to the site leads to:

> This site can’t be reached
> ERR_TIMED_OUT

The `/var/log/apache2/error.log` log contains:

```
Error: .onLoad failed in loadNamespace() for 'opencpu', details:
  call: NULL
  error: Config contains invalid JSON: /etc/opencpu/server.conf
 From directive RSourceOnStartup on line 7 of /etc/apache2/sites-enabled/opencpu.conf.
Error: .onLoad failed in loadNamespace() for 'opencpu', details:
  call: NULL
  error: Config contains invalid JSON: /etc/opencpu/server.conf
 From directive RSourceOnStartup on line 7 of /etc/apache2/sites-enabled/opencpu.conf.
``` 
2. db schema import fails

* How to reproduce

Attempt to import the sql schema: `mysql formr -uformr -p < /var/www/formr.org/sql/schema.sql`

* Expected behavior

Schema successfully imported

* Actual behavior

Import fails:

```
$ mysql formr -uformr -p < /var/www/formr.org/sql/schema.sql
Enter password:
ERROR 1060 (42S21) at line 109: Duplicate column name 'first_name'
```

Sorry to have to bother you with this, any assistance would be much appreciated.

**Comment by rubenarslan** [comment]
Regarding your first point, I just fixed the path: https://github.com/rubenarslan/formr.org/blob/master/INSTALLATION.md

**Comment by smcgrat** [comment]
Thank you

**Comment by smcgrat** [comment]
I managed to get around the mysql error by checking out the master branch instead of the `git fetch --tags && git checkout v0.18.0 -b v0.18.0` which was in the instructions and I think is still the most recent version.

**Comment by doomlab** [comment]
@smcgrat - I had that problem too with the checkout, definitely use the master branch for sql related reasons later. I wrote a how-to blog if you get stuck somewhere else. The current set up is a mix of apache2 and nginx, which I have some instructions on the bottom how to make sure they don't interact: https://www.aggieerin.com/post/formr-installation-instructions/.

**Comment by smcgrat** [comment]
> @smcgrat - I had that problem too with the checkout, definitely use the master branch for sql related reasons later. I wrote a how-to blog if you get stuck somewhere else. The current set up is a mix of apache2 and nginx, which I have some instructions on the bottom how to make sure they don't interact: https://www.aggieerin.com/post/formr-installation-instructions/.

Thanks Erin, I found your post very helpful
