### ISSUE TITLE
Overview script can't access run nor surveys data : "object not found"

### ISSUE THREAD

**Issue by Rhydderch** [rubenarslan/formr.org#455]
Hello,

I am trying to use the overview script feature.
It seems that when using "survey_name" or even "survey_unit_sessions", I can't access the data.

```{r}
 # Intersperse Markdown with R
library(formr)

length(survey_unit_sessions[survey_unit_sessions$position == 220,]$created)

nrow(enrolling_survey)
nrow(EF_RUM_ESM) # get the number of entries
        table(is.na(EF_RUM_ESM$ended)) # get finished/unfinished entries
        table(is.na(EF_RUM_ESM$modified)) # get entries where any data was entered vs not
        library(ggplot2)
        qplot(EF_RUM_ESM$created) # plot entries by startdate
```
results in:

![image](https://user-images.githubusercontent.com/3197629/96418878-aa7d5e00-11f3-11eb-924a-efe7dbd06f6f.png)

I think this would be easily reproducible with any run if it's a general bug?

Kind regards,
Yorgo

**Comment by cyriltata** [comment]
For the overview script it is best to use the API

**Comment by Rhydderch** [comment]
Okay, thanks. I will send you an email now regarding the credentials.
