### ISSUE TITLE
Registration link not being received

### ISSUE THREAD

**Issue by wRONgR** [rubenarslan/formr.org#456]
I tried to sign up to formR today. I initially used my gmail account, but did not receive a confirmation email. I clicked on 'send again' link, but did not receive the verification email.
I then signed up sequentially using two other emails via different browsers. Both email addresses are MS linked. Again, I did not receive the verification emails. I checked the spam folders in all three cases, no email. 

Could you please have a look and verify that your verification emails for sign-up are going out correctly?

**Comment by cyriltata** [comment]
@wRONgR please could you check your  spam folders the next time? I am closing this issue because I can confirm registration emails are being sent out.
