### ISSUE TITLE
Failed proper ending

### ISSUE THREAD

**Issue by valentinaandrade** [rubenarslan/formr.org#472]
Hi @rubenarslan 
I hope you are well. I don't know if this is my mistake or rather a bug in the package, but anyway I'm in doubt how to fix it, since I didn't find any documentation about this. I have tried to fix it in several ways, but I have not been able to fix it.

When I finish the survey I get this message.
* Oops, this study's creator forgot to give it a proper ending, user ayuXXXQlBAQBiyIUxz18_WHTcxBmNoWeHLtSccRPL3ZYS-ak-2nlJm3c-_KwrTuJ is dangling at the end.*

My url is https://learn-r.formr.org/

The strange thing is that I end the survey as you put it in the googlesheets template.

**Comment by rubenarslan** [comment]
Hi, in the run you always have to end with a "Stop button" module, you can't just end on a survey. I assume you didn't know this. If you did this and still got the error, please reopen the issue!

**Comment by valentinaandrade** [comment]
Hi @rubenarslan ¡Thank you very much!
Thank you for the indication, in fact I did not know it. It happened to me that the word "Stop" was not intuitive to what I was looking for. 

I have other questions, but not related to this topic, where would you prefer to ask them? I just hope I am not being a trouble for you.

**Comment by rubenarslan** [comment]
Hi! Here's our resources for help. For general support questions, the mailing list is best, especially as I'm about to be away for 2 weeks.
https://formr.org/documentation#help
