### ISSUE TITLE
Diary Study in FormR

### ISSUE THREAD

**Issue by cmraz3r** [rubenarslan/formr.org#474]
Dear guys,

I want to create a diary study with formR.
For this, I will start with a "baseline survey" everyone have to start with.
In the baseline survey, the user will enter theire e-mail adress on which they get send a notification to start a second survey (diary study) on the next day at 7 am. 
Now I tried to create a run in formR. First I set the baseline survey. After this I have placed a wait until a date when the diary study should start. Next I placed an e-mail notification at 7 am for the users, who take part in the second survey. 
Next I placed the second survey on the run in formR. The problem when I tried this construction is, that it doesnt send an e-mail to the user. 
Can anyone please give me an example of an run order when I want to make a diary study which starts with a baseline survey and then there will be about 5 more surveys on several days? Thanks a lot!

Greetings...

**Comment by rubenarslan** [comment]
Please write to the Google group with help requests. https://groups.google.com/g/formr/ This is for error reports and the like.
