### ISSUE TITLE
using `formr_connect( )` with keyring is missing the retrieval of username for `key_get( )`

### ISSUE THREAD

**Issue by j-5chneider** [rubenarslan/formr.org#475]
When I try to use
`formr_connect(keyring = "my_keyring_name" )`
R throughs me
`Fehler in b_wincred_i_get(target) : 
  Windows credential store error in 'get': Element nicht gefunden.`

It seems that I also have to specify the username. See issue:
https://community.rstudio.com/t/issue-making-a-database-connection-with-keyring/15737/7

So what works fine is
`keyring::key_get('my_keyring_name', 'the_email_I_specified')`

In the `formr_connect` function however, only `password <- keyring::key_get(keyring)` is specified, missing the username. It would have to be: `password <- keyring::key_get(keyring, keyring::key_list(keyring)[["username"]])`

So my current workaround is (super lengthy I guess...):

    formr_connect(email = keyring::key_list(service = 'my_keyring_name')[, "username"], 
                  password = keyring::key_get("my_keyring_name", keyring::key_list(service = 'my_keyring_name')[, "username"]))

If you want to adopt this workaround you'd only need to replace `my_keyring_name` with your keyring name.

Cheers
Jürgen

**Comment by rubenarslan** [comment]
Hi Jürgen, can you confirm the update works?

**Comment by j-5chneider** [comment]
Yes! Very nice, thanks!
