### ISSUE TITLE
formr surveys only display 4 choices to answer instead of 5

### ISSUE THREAD

**Issue by QueerResilienceStudy** [rubenarslan/formr.org#488]
Hey,

we just started to publish a study via formr. It turns out that even though the google sheet we used to develop the questionnaire contains more than 4 answers per question only the first 4 are displayed (instead of 5) and are eligible for participants. How can we fix this? 
Thanks for your support,
Paula

**Comment by rubenarslan** [comment]
Hi, please post to the mailing list with a reproducible example (i.e., your item spreadsheet).
