### ISSUE TITLE
 Question/Code:  Error: error (missing GET param):

### ISSUE THREAD

**Issue by javob** [rubenarslan/formr.org#490]
When testing a survey using a clone of the example spreadsheet https://docs.google.com/spreadsheets/d/1vXJ8sbkh0p4pM5xNqOelRUmslcq2IHnY9o52RmQLKFw/ 

I get the following error: 
Question/Code:  Error: error (missing GET param): 

According to the file, we would expect being randomly assign to the picture of a puppy or cat, but nothing appears.

**Comment by cyriltata** [comment]
@javob the item is not marked as optional so you need specificy it in the URL.
