### ISSUE TITLE
Update to v0.20.5 might have partially broken the random item type

### ISSUE THREAD

**Issue by martinmodrak** [rubenarslan/formr.org#494]
It looks like that around yesterday one of my surveys stopped working. The change appears to be that a random item without an explicit min/max setting (i.e. just `random` in the `type` column) that should according to documentation result in a 0 or 1 now can produce large values.  When rendered this results in the following error message:

> 2022-10-22 14:13:24: An error occurred while trying to save your survey data. Please notify the author of this survey with this date and time
> SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'covid_cases_pos' at row 1

The time last people got their random numbers generated correctly seems to be just before the commit at https://github.com/rubenarslan/formr.org/commit/ad40d8ff12c6ff1b9d2dc05d9a2c5cb15d9e1dd2
which indeed appears to change [application/Model/Item/Random.php](https://github.com/rubenarslan/formr.org/commit/ad40d8ff12c6ff1b9d2dc05d9a2c5cb15d9e1dd2#diff-31f50d184352f99b1f9ccf5efb28126df2b36d68420aa4f2e67bd123275a191d) in a way that could alter this behaviour.

I can get rid of the problem by modifying the column type to have explicit min/max `random 0,1` but reuploding the form with this will delete the previous column values.

Currently still investigating details, but it appears potentially breaking for more people, so posting without delay.

**Comment by cyriltata** [comment]
@martinmodrak thanks for pointing this out. The intention was to set as default min=>0, max=>1 but obviously some typo added the zeros. I will close this issue now
