### ISSUE TITLE
Update INSTALLATION.MD ?

### ISSUE THREAD

**Issue by jvanalst** [rubenarslan/formr.org#500]
The setup instructions appear to be out of date and contain numerous errors:

- get_magic_quotes_gpc isn't compatible with PHP 8, but the instructions say PHP >= 8.1
 - PHP mysql-pdo and pdo  are dependencies, but not listed in the list of PHP modules.
 - there is no config-dist folder anymore. It appears to have been renamed. It's also not clear from the existing instructions where to copy your config files to/from.

**Comment by jvanalst** [comment]
Also instructions on how to run it behind a reverse proxy or docker container with port forwarding would be helpful. I had to find the define_root/doc_root setting myself. The other settings in define_root aren't well documented either.

**Comment by jvanalst** [comment]
Also the links, assets, etc. don't work if you follow the instructions as written.

If I symlink /var/www/html/formr -> /var/www/formr.org/webroot there's no .htaccess visible to the Apache2 WebServer. As such the mod_rewrite rewrites don't work. As such all the links, assets, etc. are broken. This is because the .htaccess file is in /var/www/formr.org instead of /var/www/formr.org/webroot/.

If I copy the .htaccess file to webroot it breaks because **mod_header** isn't a listed as a dependency, even though it is. 

That also doesn't fix the routing. Now it just 404s on everything because it's trying to rewrite all the paths to webroot/index.php?route=$1 ... but webroot/index.php doesn't exist to Apache2 because webroot is symlinked directly to formr.

**Comment by jvanalst** [comment]
Aaaaand on my walk home I realized there may be a difference between the HEAD documentation (what you see by default on the web) and the v10.0.5 documentation. Low and behold:
[https://github.com/rubenarslan/formr.org/blob/v10.0.5/documentation/install.md](https://github.com/rubenarslan/formr.org/blob/v10.0.5/documentation/install.md)

**Comment by NS21fpsy** [comment]
Hi jvanalst
I read your posts here and saw that you are trying to do a container based installation. This is something I will probably look into for our researchers as well.
However, I have just noticed that you may be mistaken about the versions, or why are you using a version from 6 years ago? The latest tag is 0.25.5 and v10.0.5 was probably just a typo, don't you think?

https://github.com/rubenarslan/formr.org/tags --> v0.20.5 is the newest

https://github.com/rubenarslan/formr.org/tags?after=v0.10.9 --> v10.0.5 is from 2016!

Kind regards
