### ISSUE TITLE
Test run and live run don't work 

### ISSUE THREAD

**Issue by WanderingClouds** [rubenarslan/formr.org#506]
Hey there, 

Unfortunately, the test run module doesn't work, nor the live survey. When you fill out the first page and submit, you get redirected back to the first page. You are unable to test more than the first page. I tried to run my previous survey that is still live, and that doesn't work either, I ran into the same problem. Could you please help me with this? 

Thank you in advance. 

Alex

**Comment by rubenarslan** [comment]
Hi Alex,

I don't know if you're talking about self-hosting, the main formr.org instance, what account you're registered under, which studies are showing the problem. I certainly cannot reproduce the problem on our main machine. From what I little have, it sounds like cookie trouble. 

Best,

Ruben
