### ISSUE TITLE
Can't access formr from R

### ISSUE THREAD

**Issue by TarJae** [rubenarslan/formr.org#524]
I follow the instructions [here](https://github.com/rubenarslan/formr.org/wiki/Import-your-data-to-R-using-the-%60formr%60-package) to get access to my formr account from RStudio. The code I used is as follows:

```
library(formr)
formr::formr_connect()
Enter your email: my_email@gmail.com
Enter your password: my_password
```
I get this error: 
```
Error in formr::formr_connect() : Incorrect credentials.
In addition: Warning message:
In formr::formr_connect() :
  Please use the keyring package via the formr_store_keys() function instead of specifying email and password in plaintext.
```
I believe this issue might be related to the difference between:

1.<https://formr.org>
2. <https://workshops.formr.org>

While my credentials work for option 2, they do not for option 1 when I try to access via my browser.

Could someone explain the difference between these two links? And why might my credentials work for one but not the other?

**Comment by igorduartt** [comment]
Hey, same problem here. I'll be following more news on this issue. Thank you!
