### ISSUE TITLE
Error: lexical error: invalid char in json text.  <!DOCTYPE html> <html>     <hea  (right here) ------^

### ISSUE THREAD

**Issue by TarJae** [rubenarslan/formr.org#525]
After successfully getting connected to my `formr` account using this approach <https://github.com/rubenarslan/formr.org/issues/524>

and trying to fetch the responses with: 
```
survey_data <- formr::formr_raw_results("my_study")
```
I get this error: 
```
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html>     <hea
                     (right here) ------^
```
I found this: <https://stackoverflow.com/questions/41000112/reading-a-json-file-in-r-lexical-error-invalid-char-in-json-text>
"That can happen if you're trying to access an API and it's redirecting you to a login page, or a 'access forbidden' page, or similar, or if the server is down and instead of giving you JSON data, it gives you a message like "Server down for maintenance", fromJSON() doesn't know how to handle that."

Another guess of mine is, it is because of the underline in the name of the study?
Any help appreciated!

**Comment by rubenarslan** [comment]
Please read the documentation, you need to repeat the `host` argument in every function call.

**Comment by TarJae** [comment]
Thank you immensely for your patience. I noticed a note in the documentation within the example section that reads as follows:
```
## Not run: 
formr_raw_results(survey_name = 'training_diary' )

## End(Not run)
```
This explains why I was confused about the host. However, the clarification was actually provided in the preceding lines. My apologies for the oversight.

Now, when I attempt the following:
```
formr::formr_raw_results(survey_name = 'my_study', host = "https://workshops.formr.org")
```
I encounter this error:
```
Error: parse error: premature EOF
                                       
                     (right here) ------^
```
I greatly appreciate your patience and assistance!
