### ISSUE TITLE
Email stopped working

### ISSUE THREAD

**Issue by abruegger** [rubenarslan/formr.org#537]
The email functionality in my account on formr.org stopped working. First  I thought it was because the provider changed something. But after trying different email accounts and consistently getting the same error message, I'm wondering if there is something wrong with my formr account. 

Any ideas what could be happening here?

Here are two examples:
![grafik](https://github.com/rubenarslan/formr.org/assets/31000762/1c507fbe-4d1e-4ab6-bf99-533145950ccf)

![grafik](https://github.com/rubenarslan/formr.org/assets/31000762/d8eee44a-26ed-4580-bd3f-1d60b5f73eb4)

**Comment by rubenarslan** [comment]
I can still send emails using formr.org. Gmail was always difficult to get to work because they have fairly stringent guards against automatic email sending. Uni Bern recently switched to the Microsoft Cloud. It seems they might have started requiring OAuth. You should ask your local IT.

**Comment by abruegger** [comment]
No luck with either Uni Bern nor Gmail. I tried a third email, varied various ports. 

For future users: The combination **SMTP 465 and TLS "no" worked.**

**Comment by rubenarslan** [comment]
Future users: you have to use the right settings for your host. Most common these days is 587 tls. There is no single set of correct settings and there are an increasing number of service providers that limit automated email sending.
