### ISSUE TITLE
Alert "too many empty pages"

### ISSUE THREAD

**Issue by mpreis2** [rubenarslan/formr.org#544]
### Discussed in https://github.com/rubenarslan/formr.org/discussions/543

<div type='discussions-op-text'>

<sup>Originally posted by **mpreis2** April 30, 2024</sup>
Hey everyone,

In my study participants complete a questionnaire repeatedly at three measurement points. The questionnaire consists of 36 scenarios. After each scenario, three possible interpretations of the scenario appear in a randomized order and the participants need to rate how much they agree with each possible interpretation. At each of the three measurement points only a subset of twelve scenarios is shown and the order of the subsets per measurement point should be counterbalanced. 

That’s why I divided all participants into three groups (via the shuffle function) before the first questionnaire and used the “show if” function in the questionnaire (shuffle$group == 1 for the first subset of scenarios, shuffle$group == 2 for the second subset of scenarios, shuffle$group == 3 for the third subset of scenarios).
If I use the “test run” function, I get the alert “too many empty pages in this survey. Please alert an administrator”. If I then use the refresh button, it takes some time but then the questionnaire is displayed correctly and the answers are saved as well. 

I think the problem has something to do with the high number of “show ifs” used in the questionnaire because if I was assigned to shufflegroup 1, the questionnaire works till the last item and the alert only shows after that. At that time the mass of “show ifs” begins in the questionnaire for this group. If I was assigned to shufflegroup 2 or 3, the alert appears after the instruction, which is the time when the mass of “show ifs” begin for these two groups.

I found three earlier conversations in the google group concerning this alert and one member (j_ 5chneider, 30.09.2029) suggested a similar explanation. However, I did not find a solution for the problem.

I included a minimal json file and the google sheet of the questionnaire (https://docs.google.com/spreadsheets/d/19sC2Kd4mdoXk8grd4K-ZOVeucU3n3M6ZAdTnPMAkIk4/edit#gid=0) and would be thrilled if you could help me out. 

[ideal_IB_test.json](https://github.com/rubenarslan/formr.org/files/15160559/ideal_IB_test.json)

Thanks a lot, and best wishes 
Mira
</div>

**Comment by mpreis2** [comment]
Hey everyone,
just a little update to clarify the problem: 
If you are randomized to shuffle$group == 2, the questionnaire has a very long loading time, but it works. So, the alert "too many empty pages in this survey. Please alert an administrator” only appears for shuffle group 1 at the end of the survey and for shuffle group 3 at the beginning (after the instruction). This confirms my suspicion that the problem must be the large number of "show ifs".
I would be very happy for any ideas that might help!

**Comment by rubenarslan** [comment]
I don't know why this happens, I guess some unfortunate interaction of showif + block order. Can you just separate the survey into three and randomize at the run level? 
E.g. SkipForward shuffle$group == 2 jumps to Survey 2 etc.

**Comment by mpreis2** [comment]
Thanks for your quick response.
Randomizing at the run level was my backup plan. It is a bit more complex but it will work. :-)

**Comment by cyriltata** [comment]
Dear Mira

In case you haven't engaged in the solution provided by Ruben, you can try
to add a "note" item, in between where you have consecutive "submit" items.
For example: Between rows 14&15, 27&28, 40&41 etc..

best
Cyril

**Comment by mpreis2** [comment]
Dear Cyril,

thanks, I already created three surveys out of the one and use the skip function. This works perfectly.

Best
Mira
Von: Cyril ***@***.***>
Gesendet: Donnerstag, 2. Mai 2024 11:10
An: rubenarslan/formr.org ***@***.***>
Cc: Preis, Mira ***@***.***>; Author ***@***.***>
Betreff: Re: [rubenarslan/formr.org] Alert "too many empty pages" (Issue #544)

Dear Mira

In case you haven't engaged in the solution provided by Ruben, you can try
to add a "note" item, in between where you have consecutive "submit" items.
For example: Between rows 14&15, 27&28, 40&41 etc..

best
Cyril
