### ISSUE TITLE
0 badly handled as item number boundary

### ISSUE THREAD

**Issue by courtiol** [rubenarslan/formr.org#582]
The **number** input field from the "Simple input family" can be defined as "min, max, step" according to the documentation.

The problem is that if one enters `0,100,1` the `0` is silently ignored.
If one enters instead `0.0,100,1` or `00,100,1`, it does work as workaround.

This shows that internally 0 is treated differently than other numbers (usually makes sense but not here).

Notes:
- the same bug applies when the max is 0 and not the min.
- the same bug also applies for the pre-set value associated with the same input (but then workaround leads to a display of 0.0 or 00 in the input field, which looks weird)).

Reprex:
- https://docs.google.com/spreadsheets/d/1PifEmsbYEfGpHASceW-cVdW5rlILUO9Lo6iVKLbvXRk/edit?gid=0#gid=0
- https://reproducing-issue-582.rforms.org/

**Comment by rubenarslan** [comment]
Thanks for the great reproducible example. It will be fixed in the next release.
