### ISSUE TITLE
allow disabling emails from formr and specific studies

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#81]
we already have the field `no_email` in the survey_run_sessions table. Basically, all emails should have a unsubscribe message at the bottom, along the lines of:

I do not want to get emails from this study ever again / for two weeks. I do not want emails at all.

maybe also establish an automated way of deleting data associated with a specific user?

**Comment by rubenarslan** [comment]
We will define no_email as a INT/timestamp, if it's NULL we send emails, if it's 0 we don't, if it's a timestamp we wait.

**Comment by cyriltata** [comment]
There should be a "settings" page for all runs where such things can be configured by user (identified by code) The link in the email should link to this page. The settings page could also contain other things like deleting cookie, ..etc

**Comment by cyriltata** [comment]
ab1853cb5839f1a28738137468123f8ab1802982
